/*
# Enrich Personalities Batch A: Major Emperors and Key Figures

1. Purpose
Populates all fields for the most prominent historical figures in the database:
Chandragupta Maurya, Ashoka the Great, Chanakya, Samudragupta, Aryabhata,
Kalidasa, Rajaraja Chola I, Shivaji, Mahatma Gandhi, and Buddha (Siddhartha Gautama).

These 10 records are the "featured" personalities that already had partial data
(role, era, legacy) and are the most historically significant figures in the
database. This migration completes their records with all available fields.

2. Fields Populated
- slug, title, gender, birth_year, death_year, birth_text, death_text
- categories, civilization, historical_period, dynasty, kingdom, religion, occupation
- birthplace, death_place, region, present_state, present_country
- short_description, famous_for, achievements, notable_works, notable_titles
- active_start_year, active_end_year, century, timeline_order
- father, mother, spouse, children, teacher, students, predecessor, successor, contemporaries, related_people
- related_events, related_dynasties, related_kingdoms
- wikipedia_url, keywords, search_aliases, meta_description
- verified, featured, updated_at

3. Historical Accuracy
All dates, relationships, and facts are based on established historical scholarship.
BCE years stored as negative integers. Unknown values left as NULL.
Epic/legendary figures (Krishna, Arjuna, etc.) are marked with verified=false.
*/

-- p1: Chandragupta Maurya
UPDATE personalities SET
  slug = 'chandragupta-maurya',
  title = 'Emperor',
  gender = 'Male',
  birth_year = -350,
  death_year = -297,
  birth_text = 'c. 350 BCE',
  death_text = 'c. 297 BCE',
  categories = ARRAY['Ruler','Military','Administrator'],
  civilization = 'Mauryan Empire',
  historical_period = 'Ancient India',
  dynasty = 'Maurya Dynasty',
  kingdom = 'Magadha',
  religion = 'Jainism',
  occupation = ARRAY['Emperor','Ruler'],
  birthplace = 'Pataliputra',
  death_place = 'Shravanabelagola',
  region = 'Magadha',
  present_state = 'Bihar',
  present_country = 'India',
  short_description = 'Chandragupta Maurya was the founder of the Mauryan Empire and unified much of the Indian subcontinent during the late fourth century BCE.',
  famous_for = 'Founded the Mauryan Empire with guidance from Chanakya. Established the first pan-Indian political entity.',
  achievements = ARRAY['Founded the Mauryan Empire','Unified most of the Indian subcontinent','Defeated Seleucus I Nicator','Established centralized administration'],
  notable_works = ARRAY[]::TEXT[],
  notable_titles = ARRAY['Emperor','Maharaja'],
  active_start_year = -321,
  active_end_year = -297,
  century = '4th century BCE',
  timeline_order = 1,
  father = NULL,
  mother = NULL,
  spouse = NULL,
  children = ARRAY['Bindusara'],
  teacher = ARRAY['Chanakya'],
  students = ARRAY[]::TEXT[],
  predecessor = NULL,
  successor = 'Bindusara',
  contemporaries = ARRAY['Chanakya','Seleucus I Nicator','Megasthenes'],
  related_people = ARRAY['Chanakya','Bindusara','Seleucus I Nicator'],
  related_events = ARRAY['e4'],
  related_dynasties = ARRAY['Maurya Dynasty'],
  related_kingdoms = ARRAY['Magadha'],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Chandragupta_Maurya',
  keywords = ARRAY['Chandragupta Maurya','Mauryan Empire','Magadha','Chanakya','Ancient India','Jainism','Shravanabelagola'],
  search_aliases = ARRAY['Chandragupta','Sandrocottus'],
  meta_description = 'Chandragupta Maurya founded the Mauryan Empire and unified most of the Indian subcontinent in the late fourth century BCE.',
  verified = TRUE,
  featured = TRUE,
  updated_at = NOW()
WHERE id = 'p1';

-- p2: Ashoka the Great
UPDATE personalities SET
  slug = 'ashoka-the-great',
  title = 'Emperor',
  gender = 'Male',
  birth_year = -304,
  death_year = -232,
  birth_text = 'c. 304 BCE',
  death_text = 'c. 232 BCE',
  categories = ARRAY['Ruler','Administrator','Religious Patron'],
  civilization = 'Mauryan Empire',
  historical_period = 'Ancient India',
  dynasty = 'Maurya Dynasty',
  kingdom = 'Magadha',
  religion = 'Buddhism',
  occupation = ARRAY['Emperor','Ruler'],
  birthplace = 'Pataliputra',
  death_place = 'Pataliputra',
  region = 'Magadha',
  present_state = 'Bihar',
  present_country = 'India',
  short_description = 'Ashoka was the third Mauryan emperor whose reign transformed Indian history through administrative reforms and the promotion of Buddhism.',
  famous_for = 'Spread Buddhism across Asia through royal patronage and rock edicts after the Kalinga War. His policy of dhamma influenced governance across the subcontinent.',
  achievements = ARRAY['Conquered Kalinga','Promoted Buddhism through royal patronage','Issued rock and pillar edicts','Established welfare policies for subjects'],
  notable_works = ARRAY['Rock Edicts','Pillar Edicts'],
  notable_titles = ARRAY['Emperor','Devanampiya Piyadasi','Maharaja'],
  active_start_year = -268,
  active_end_year = -232,
  century = '3rd century BCE',
  timeline_order = 2,
  father = 'Bindusara',
  mother = NULL,
  spouse = NULL,
  children = ARRAY['Mahinda','Sanghamitta','Kunala'],
  teacher = ARRAY[]::TEXT[],
  students = ARRAY[]::TEXT[],
  predecessor = 'Bindusara',
  successor = 'Dasaratha Maurya',
  contemporaries = ARRAY['Megasthenes','Bindusara'],
  related_people = ARRAY['Chandragupta Maurya','Bindusara','Mahinda','Sanghamitta'],
  related_events = ARRAY['e5','e17'],
  related_dynasties = ARRAY['Maurya Dynasty'],
  related_kingdoms = ARRAY['Magadha'],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Ashoka',
  keywords = ARRAY['Ashoka','Mauryan Empire','Kalinga War','Buddhism','Edicts','Dhamma','Ancient India','Magadha'],
  search_aliases = ARRAY['Asoka','Devanampiya Piyadasi'],
  meta_description = 'Ashoka was the third Mauryan emperor whose reign transformed Indian history through administrative reforms and the promotion of Buddhism.',
  verified = TRUE,
  featured = TRUE,
  updated_at = NOW()
WHERE id = 'p2';

-- p3: Chanakya
UPDATE personalities SET
  slug = 'chanakya',
  title = 'Acharya',
  gender = 'Male',
  birth_year = -375,
  death_year = -283,
  birth_text = 'c. 375 BCE',
  death_text = 'c. 283 BCE',
  categories = ARRAY['Scholar','Administrator','Strategist'],
  civilization = 'Mauryan Empire',
  historical_period = 'Ancient India',
  dynasty = NULL,
  kingdom = 'Magadha',
  religion = 'Hinduism',
  occupation = ARRAY['Scholar','Strategist','Minister'],
  birthplace = 'Takshashila',
  death_place = 'Pataliputra',
  region = 'Magadha',
  present_state = 'Bihar',
  present_country = 'India',
  short_description = 'Chanakya was a scholar, strategist, and royal advisor who authored the Arthashastra and was the principal architect of the Mauryan Empire.',
  famous_for = 'Authored the Arthashastra, a foundational treatise on statecraft and economics. Guided Chandragupta Maurya to establish the Mauryan Empire.',
  achievements = ARRAY['Authored the Arthashastra','Architect of the Mauryan Empire','Served as chief advisor to Chandragupta Maurya'],
  notable_works = ARRAY['Arthashastra','Nitishastra'],
  notable_titles = ARRAY['Acharya','Guru','Minister'],
  active_start_year = -330,
  active_end_year = -283,
  century = '4th century BCE',
  timeline_order = 1,
  father = NULL,
  mother = NULL,
  spouse = NULL,
  children = NULL,
  teacher = ARRAY[]::TEXT[],
  students = ARRAY['Chandragupta Maurya'],
  predecessor = NULL,
  successor = NULL,
  contemporaries = ARRAY['Chandragupta Maurya','Bindusara','Seleucus I Nicator'],
  related_people = ARRAY['Chandragupta Maurya','Bindusara'],
  related_events = ARRAY['e4','e18'],
  related_dynasties = ARRAY['Maurya Dynasty'],
  related_kingdoms = ARRAY['Magadha'],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Chanakya',
  keywords = ARRAY['Chanakya','Arthashastra','Mauryan Empire','Statecraft','Economics','Ancient India','Takshashila','Kautilya'],
  search_aliases = ARRAY['Kautilya','Vishnugupta'],
  meta_description = 'Chanakya authored the Arthashastra and was the principal architect of the Mauryan Empire under Chandragupta Maurya.',
  verified = TRUE,
  featured = TRUE,
  updated_at = NOW()
WHERE id = 'p3';

-- p4: Samudragupta
UPDATE personalities SET
  slug = 'samudragupta',
  title = 'Emperor',
  gender = 'Male',
  birth_year = NULL,
  death_year = 380,
  birth_text = NULL,
  death_text = 'c. 380 CE',
  categories = ARRAY['Ruler','Military','Patron of Arts'],
  civilization = 'Gupta Empire',
  historical_period = 'Classical India',
  dynasty = 'Gupta Dynasty',
  kingdom = 'Magadha',
  religion = 'Hinduism',
  occupation = ARRAY['Emperor','Ruler'],
  birthplace = 'Pataliputra',
  death_place = 'Pataliputra',
  region = 'Magadha',
  present_state = 'Bihar',
  present_country = 'India',
  short_description = 'Samudragupta was a Gupta emperor who expanded the empire across northern India and patronized the arts during the Golden Age of classical India.',
  famous_for = 'Expanded the Gupta Empire through military conquests across northern and central India. Patronized scholars, poets, and musicians.',
  achievements = ARRAY['Expanded the Gupta Empire across northern India','Conquered numerous kingdoms across the subcontinent','Patronized arts and scholarship','Performed Ashvamedha sacrifice'],
  notable_works = ARRAY[]::TEXT[],
  notable_titles = ARRAY['Emperor','Maharajadhiraja','Napoleon of India'],
  active_start_year = 335,
  active_end_year = 380,
  century = '4th century CE',
  timeline_order = 10,
  father = 'Chandragupta I',
  mother = NULL,
  spouse = NULL,
  children = ARRAY['Chandragupta II Vikramaditya'],
  teacher = ARRAY[]::TEXT[],
  students = ARRAY[]::TEXT[],
  predecessor = 'Chandragupta I',
  successor = 'Chandragupta II Vikramaditya',
  contemporaries = ARRAY['Kalidasa','Varahamihira'],
  related_people = ARRAY['Chandragupta I','Chandragupta II Vikramaditya','Kalidasa'],
  related_events = ARRAY['e6'],
  related_dynasties = ARRAY['Gupta Dynasty'],
  related_kingdoms = ARRAY['Magadha'],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Samudragupta',
  keywords = ARRAY['Samudragupta','Gupta Empire','Golden Age','Magadha','Ancient India','Ashvamedha','Conquest'],
  search_aliases = ARRAY['Napoleon of India'],
  meta_description = 'Samudragupta expanded the Gupta Empire across northern India and patronized the arts during the Golden Age of classical India.',
  verified = TRUE,
  featured = TRUE,
  updated_at = NOW()
WHERE id = 'p4';

-- p5: Aryabhata
UPDATE personalities SET
  slug = 'aryabhata',
  title = 'Mathematician',
  gender = 'Male',
  birth_year = 476,
  death_year = 550,
  birth_text = '476 CE',
  death_text = 'c. 550 CE',
  categories = ARRAY['Scientist','Mathematician','Astronomer'],
  civilization = 'Gupta Empire',
  historical_period = 'Classical India',
  dynasty = NULL,
  kingdom = NULL,
  religion = 'Hinduism',
  occupation = ARRAY['Mathematician','Astronomer'],
  birthplace = 'Kusumapura',
  death_place = NULL,
  region = 'Magadha',
  present_state = 'Bihar',
  present_country = 'India',
  short_description = 'Aryabhata was a mathematician and astronomer who introduced the place-value system and approximated pi in the Aryabhatiya during the fifth century CE.',
  famous_for = 'Composed the Aryabhatiya, introducing the place-value system, approximation of pi, and foundations of trigonometry.',
  achievements = ARRAY['Introduced the place-value number system','Approximated pi to four decimal places','Described the rotation of Earth on its axis','Developed foundations of trigonometry','Calculated the length of the solar year'],
  notable_works = ARRAY['Aryabhatiya','Arya-siddhanta'],
  notable_titles = ARRAY['Mathematician','Astronomer','Acharya'],
  active_start_year = 499,
  active_end_year = 550,
  century = '5th-6th century CE',
  timeline_order = 12,
  father = NULL,
  mother = NULL,
  spouse = NULL,
  children = NULL,
  teacher = ARRAY[]::TEXT[],
  students = ARRAY['Bhaskara I'],
  predecessor = NULL,
  successor = NULL,
  contemporaries = ARRAY['Varahamihira','Bhaskara I'],
  related_people = ARRAY['Bhaskara I','Varahamihira','Brahmagupta'],
  related_events = ARRAY['e7'],
  related_dynasties = ARRAY[]::TEXT[],
  related_kingdoms = ARRAY[]::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Aryabhata',
  keywords = ARRAY['Aryabhata','Aryabhatiya','Mathematics','Astronomy','Pi','Trigonometry','Gupta Empire','Place-value system'],
  search_aliases = ARRAY['Aryabhatta'],
  meta_description = 'Aryabhata introduced the place-value system and approximated pi in the Aryabhatiya during the fifth century CE.',
  verified = TRUE,
  featured = TRUE,
  updated_at = NOW()
WHERE id = 'p5';

-- p6: Kalidasa
UPDATE personalities SET
  slug = 'kalidasa',
  title = 'Poet',
  gender = 'Male',
  birth_year = NULL,
  death_year = NULL,
  birth_text = 'c. 4th-5th century CE',
  death_text = 'c. 5th century CE',
  categories = ARRAY['Poet','Scholar','Dramatist'],
  civilization = 'Gupta Empire',
  historical_period = 'Classical India',
  dynasty = NULL,
  kingdom = NULL,
  religion = 'Hinduism',
  occupation = ARRAY['Poet','Dramatist'],
  birthplace = NULL,
  death_place = NULL,
  region = NULL,
  present_state = NULL,
  present_country = 'India',
  short_description = 'Kalidasa was a Sanskrit poet and dramatist widely regarded as the greatest writer in classical Sanskrit literature.',
  famous_for = 'Composed Abhijnanasakuntalam, Meghaduta, and Raghuvamsha. Considered the greatest Sanskrit poet of classical India.',
  achievements = ARRAY['Composed Abhijnanasakuntalam','Composed Meghaduta','Composed Raghuvamsha','Composed Kumarasambhava','Composed Ritusamhara'],
  notable_works = ARRAY['Abhijnanasakuntalam','Meghaduta','Raghuvamsha','Kumarasambhava','Ritusamhara','Malavikagnimitram'],
  notable_titles = ARRAY['Poet','Dramatist','Kavi'],
  active_start_year = 375,
  active_end_year = 450,
  century = '4th-5th century CE',
  timeline_order = 11,
  father = NULL,
  mother = NULL,
  spouse = NULL,
  children = NULL,
  teacher = ARRAY[]::TEXT[],
  students = ARRAY[]::TEXT[],
  predecessor = NULL,
  successor = NULL,
  contemporaries = ARRAY['Samudragupta','Chandragupta II Vikramaditya','Varahamihira'],
  related_people = ARRAY['Samudragupta','Chandragupta II Vikramaditya'],
  related_events = ARRAY['e19'],
  related_dynasties = ARRAY['Gupta Dynasty'],
  related_kingdoms = ARRAY[]::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Kalidasa',
  keywords = ARRAY['Kalidasa','Sanskrit','Poetry','Drama','Abhijnanasakuntalam','Meghaduta','Gupta Empire','Classical India'],
  search_aliases = ARRAY['Kālidāsa'],
  meta_description = 'Kalidasa was the greatest Sanskrit poet and dramatist of classical India, author of Shakuntala and Meghaduta.',
  verified = TRUE,
  featured = TRUE,
  updated_at = NOW()
WHERE id = 'p6';

-- p7: Rajaraja Chola I
UPDATE personalities SET
  slug = 'rajaraja-chola-i',
  title = 'Emperor',
  gender = 'Male',
  birth_year = 947,
  death_year = 1014,
  birth_text = 'c. 947 CE',
  death_text = '1014 CE',
  categories = ARRAY['Ruler','Military','Patron of Arts'],
  civilization = 'Chola Empire',
  historical_period = 'Medieval India',
  dynasty = 'Chola Dynasty',
  kingdom = 'Chola Nadu',
  religion = 'Hinduism',
  occupation = ARRAY['Emperor','Ruler'],
  birthplace = 'Tirukoilur',
  death_place = 'Thanjavur',
  region = 'Tamilakam',
  present_state = 'Tamil Nadu',
  present_country = 'India',
  short_description = 'Rajaraja Chola I was a Chola emperor who built the Brihadeeswara Temple and expanded Chola naval power across Southeast Asia.',
  famous_for = 'Built the Brihadeeswara Temple at Thanjavur. Expanded the Chola Empire through military conquests and naval expeditions.',
  achievements = ARRAY['Built the Brihadeeswara Temple at Thanjavur','Expanded the Chola Empire across South India','Conquered Sri Lanka','Established Chola naval power','Patronized Tamil literature'],
  notable_works = ARRAY[]::TEXT[],
  notable_titles = ARRAY['Emperor','Chola','Maharaja','Rajaraja Deva'],
  active_start_year = 985,
  active_end_year = 1014,
  century = '10th-11th century CE',
  timeline_order = 25,
  father = 'Sundara Chola',
  mother = 'Vanavan Mahadevi',
  spouse = ARRAY['Dantisakti'],
  children = ARRAY['Rajendra I Chola'],
  teacher = ARRAY[]::TEXT[],
  students = ARRAY[]::TEXT[],
  predecessor = 'Uttama Chola',
  successor = 'Rajendra I Chola',
  contemporaries = ARRAY[]::TEXT[],
  related_people = ARRAY['Rajendra I Chola','Uttama Chola','Sundara Chola'],
  related_events = ARRAY['e8','e20'],
  related_dynasties = ARRAY['Chola Dynasty'],
  related_kingdoms = ARRAY['Chola Nadu'],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Rajaraja_I',
  keywords = ARRAY['Rajaraja Chola','Brihadeeswara Temple','Thanjavur','Chola Empire','Naval power','Tamil Nadu','Medieval India'],
  search_aliases = ARRAY['Rajaraja the Great','Arulmozhivarman'],
  meta_description = 'Rajaraja Chola I built the Brihadeeswara Temple and expanded Chola naval power to Southeast Asia in the 10th-11th century.',
  verified = TRUE,
  featured = TRUE,
  updated_at = NOW()
WHERE id = 'p7';

-- p8: Shivaji
UPDATE personalities SET
  slug = 'shivaji',
  title = 'Chhatrapati',
  gender = 'Male',
  birth_year = 1630,
  death_year = 1680,
  birth_text = '1630 CE',
  death_text = '1680 CE',
  categories = ARRAY['Ruler','Military','Administrator'],
  civilization = 'Maratha Confederacy',
  historical_period = 'Early Modern India',
  dynasty = 'Bhonsle Dynasty',
  kingdom = 'Maratha Kingdom',
  religion = 'Hinduism',
  occupation = ARRAY['Emperor','Military Commander'],
  birthplace = 'Shivneri Fort',
  death_place = 'Raigad Fort',
  region = 'Maharashtra',
  present_state = 'Maharashtra',
  present_country = 'India',
  short_description = 'Shivaji was the founder of the Maratha Empire who pioneered guerrilla warfare and established a navy in western India during the seventeenth century.',
  famous_for = 'Founded the Maratha Empire. Pioneered guerrilla warfare tactics and built a naval force to challenge dominant powers in the Deccan.',
  achievements = ARRAY['Founded the Maratha Empire','Pioneered guerrilla warfare tactics','Built a Maratha navy','Coronated as Chhatrapati in 1674','Established an efficient administrative system'],
  notable_works = ARRAY[]::TEXT[],
  notable_titles = ARRAY['Chhatrapati','Maharaja','Shivaji Maharaj'],
  active_start_year = 1645,
  active_end_year = 1680,
  century = '17th century CE',
  timeline_order = 45,
  father = 'Shahaji Bhonsle',
  mother = 'Jijabai',
  spouse = ARRAY['Sai Bai','Soyarabai'],
  children = ARRAY['Sambhaji','Rajaram'],
  teacher = ARRAY['Dadaji Kondadev'],
  students = ARRAY[]::TEXT[],
  predecessor = NULL,
  successor = 'Sambhaji',
  contemporaries = ARRAY['Aurangzeb','Afzal Khan'],
  related_people = ARRAY['Sambhaji','Jijabai','Shahaji Bhonsle','Afzal Khan','Aurangzeb'],
  related_events = ARRAY['e10'],
  related_dynasties = ARRAY['Bhonsle Dynasty'],
  related_kingdoms = ARRAY['Maratha Kingdom'],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Shivaji',
  keywords = ARRAY['Shivaji','Maratha Empire','Guerrilla warfare','Chhatrapati','Raigad','Maharashtra','Hindavi Swarajya'],
  search_aliases = ARRAY['Shivaji Maharaj','Chhatrapati Shivaji'],
  meta_description = 'Shivaji founded the Maratha Empire and pioneered guerrilla warfare and a navy in seventeenth-century western India.',
  verified = TRUE,
  featured = TRUE,
  updated_at = NOW()
WHERE id = 'p8';

-- p9: Mahatma Gandhi
UPDATE personalities SET
  slug = 'mahatma-gandhi',
  title = 'Freedom Fighter',
  gender = 'Male',
  birth_year = 1869,
  death_year = 1948,
  birth_text = '1869 CE',
  death_text = '1948 CE',
  categories = ARRAY['Freedom Fighter','Social Reformer','Philosopher'],
  civilization = 'Indian Independence Movement',
  historical_period = 'Modern India',
  dynasty = NULL,
  kingdom = NULL,
  religion = 'Hinduism',
  occupation = ARRAY['Independence Leader','Social Reformer','Lawyer'],
  birthplace = 'Porbandar',
  death_place = 'New Delhi',
  region = 'Gujarat',
  present_state = 'Gujarat',
  present_country = 'India',
  short_description = 'Mahatma Gandhi led India to independence from British rule through nonviolent civil disobedience and inspired movements for civil rights across the world.',
  famous_for = 'Led India to independence through nonviolent civil disobedience. His philosophy of satyagraha influenced civil rights movements globally.',
  achievements = ARRAY['Led India to independence from British rule','Developed the philosophy of satyagraha','Led the Dandi Salt March','Led the Non-Cooperation Movement','Influenced civil rights movements worldwide'],
  notable_works = ARRAY['The Story of My Experiments with Truth','Hind Swaraj'],
  notable_titles = ARRAY['Mahatma','Father of the Nation','Bapu'],
  active_start_year = 1893,
  active_end_year = 1948,
  century = '20th century CE',
  timeline_order = 55,
  father = 'Karamchand Gandhi',
  mother = 'Putlibai Gandhi',
  spouse = ARRAY['Kasturba Gandhi'],
  children = ARRAY['Harilal','Manilal','Ramdas','Devdas'],
  teacher = ARRAY[]::TEXT[],
  students = ARRAY[]::TEXT[],
  predecessor = NULL,
  successor = NULL,
  contemporaries = ARRAY['Jawaharlal Nehru','Sardar Patel','Subhas Chandra Bose'],
  related_people = ARRAY['Jawaharlal Nehru','Sardar Patel','Kasturba Gandhi'],
  related_events = ARRAY['e13','e14'],
  related_dynasties = ARRAY[]::TEXT[],
  related_kingdoms = ARRAY[]::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Mahatma_Gandhi',
  keywords = ARRAY['Mahatma Gandhi','Independence','Nonviolence','Satyagraha','Dandi March','Freedom Movement','Porbandar','Father of the Nation'],
  search_aliases = ARRAY['Gandhi','Bapu','Mohandas Karamchand Gandhi'],
  meta_description = 'Mahatma Gandhi led India to independence through nonviolent civil disobedience and inspired civil rights movements worldwide.',
  verified = TRUE,
  featured = TRUE,
  updated_at = NOW()
WHERE id = 'p9';

-- p10: Buddha (Siddhartha Gautama)
UPDATE personalities SET
  slug = 'buddha-siddhartha-gautama',
  title = 'Spiritual Teacher',
  gender = 'Male',
  birth_year = -563,
  death_year = -483,
  birth_text = 'c. 563 BCE',
  death_text = 'c. 483 BCE',
  categories = ARRAY['Saint','Philosopher','Religious Leader'],
  civilization = 'Mahajanapada Period',
  historical_period = 'Ancient India',
  dynasty = 'Shakya',
  kingdom = 'Kapilavastu',
  religion = 'Buddhism',
  occupation = ARRAY['Spiritual Teacher','Philosopher'],
  birthplace = 'Lumbini',
  death_place = 'Kushinagar',
  region = 'Magadha',
  present_state = 'Bihar',
  present_country = 'India',
  short_description = 'Siddhartha Gautama, the Buddha, was a spiritual teacher who founded Buddhism and whose teachings spread across Asia during the fifth century BCE.',
  famous_for = 'Founded Buddhism. Attained enlightenment under the Bodhi tree at Bodh Gaya and taught the Four Noble Truths and the Eightfold Path.',
  achievements = ARRAY['Founded Buddhism','Attained enlightenment at Bodh Gaya','Taught the Four Noble Truths','Established the Eightfold Path','Founded the Buddhist monastic order'],
  notable_works = ARRAY[]::TEXT[],
  notable_titles = ARRAY['Buddha','Tathagata','Shakyamuni','Bhagavan'],
  active_start_year = -528,
  active_end_year = -483,
  century = '6th-5th century BCE',
  timeline_order = 0,
  father = 'Suddhodana',
  mother = 'Maya',
  spouse = ARRAY['Yashodhara'],
  children = ARRAY['Rahula'],
  teacher = ARRAY[]::TEXT[],
  students = ARRAY['Ananda','Sariputta','Moggallana','Mahakassapa'],
  predecessor = NULL,
  successor = NULL,
  contemporaries = ARRAY['Mahavira','Bimbisara','Ajatashatru'],
  related_people = ARRAY['Mahavira','Bimbisara','Ananda','Sariputta'],
  related_events = ARRAY['e3'],
  related_dynasties = ARRAY[]::TEXT[],
  related_kingdoms = ARRAY['Kapilavastu','Magadha'],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Gautama_Buddha',
  keywords = ARRAY['Buddha','Siddhartha Gautama','Buddhism','Enlightenment','Bodh Gaya','Four Noble Truths','Eightfold Path','Lumbini'],
  search_aliases = ARRAY['Siddhartha','Shakyamuni','Tathagata','Gautama Buddha'],
  meta_description = 'Siddhartha Gautama founded Buddhism and taught the Four Noble Truths, spreading a tradition that reshaped Asia.',
  verified = TRUE,
  featured = TRUE,
  updated_at = NOW()
WHERE id = 'p10';
