/*
# Enrich Personalities Batch C: Gupta, Kushan, and Post-Gupta Rulers

Fixes: spouse must be ARRAY type, father/mother/predecessor/successor are TEXT.
*/

-- p14: Chandragupta II Vikramaditya
UPDATE personalities SET
  slug = 'chandragupta-ii-vikramaditya', title = 'Emperor', gender = 'Male',
  birth_year = NULL, death_year = 415, birth_text = NULL, death_text = 'c. 415 CE',
  categories = ARRAY['Ruler','Military','Patron of Arts']::TEXT[],
  civilization = 'Gupta Empire', historical_period = 'Classical India',
  dynasty = 'Gupta Dynasty', kingdom = 'Magadha', religion = 'Hinduism',
  occupation = ARRAY['Emperor']::TEXT[],
  birthplace = NULL, death_place = NULL,
  region = 'Northern India', present_state = 'Bihar', present_country = 'India',
  short_description = 'Chandragupta II Vikramaditya was a Gupta emperor who ruled from approximately 380 to 415 CE, defeating the Western Kshatrapas and presiding over the Golden Age of classical India with scholars like Kalidasa at his court.',
  famous_for = 'Defeating the Western Kshatrapas and extending the Gupta Empire to its greatest extent. His court was adorned by the navaratnas including Kalidasa.',
  achievements = ARRAY['Defeated and annexed the Western Kshatrapa kingdom','Extended Gupta Empire from Oxus to Bengal','Integrated Vakataka kingdom through marriage alliance','Patronized Kalidasa and other scholars','Issued gold coins of high artistic quality']::TEXT[],
  notable_works = ARRAY[]::TEXT[], notable_titles = ARRAY['Vikramaditya','Maharajadhiraja']::TEXT[],
  active_start_year = 380, active_end_year = 415, century = '4th-5th century CE', timeline_order = 10,
  father = 'Samudragupta', mother = 'Dattadevi', spouse = ARRAY['Dhruvadevi']::TEXT[],
  children = ARRAY['Kumaragupta I','Prabhavatigupta']::TEXT[],
  teacher = NULL, students = NULL,
  predecessor = 'Samudragupta', successor = 'Kumaragupta I',
  contemporaries = ARRAY['Kalidasa','Varahamihira']::TEXT[],
  related_people = ARRAY['Samudragupta','Kumaragupta I','Kalidasa']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Gupta Dynasty','Vakataka']::TEXT[],
  related_kingdoms = ARRAY['Magadha']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Chandragupta_II',
  keywords = ARRAY['Chandragupta II','Vikramaditya','Gupta Empire','Golden Age','Kalidasa']::TEXT[],
  search_aliases = ARRAY['Chandragupta Vikramaditya']::TEXT[],
  meta_description = 'Chandragupta II Vikramaditya (c. 380-415 CE) was the greatest Gupta emperor who presided over the Golden Age of classical India.',
  verified = TRUE, featured = TRUE, updated_at = NOW()
WHERE id = 'p14';

-- p15: Kumaragupta I
UPDATE personalities SET
  slug = 'kumaragupta-i', title = 'Emperor', gender = 'Male',
  birth_year = NULL, death_year = 455, birth_text = NULL, death_text = 'c. 455 CE',
  categories = ARRAY['Ruler','Patron of Education']::TEXT[],
  civilization = 'Gupta Empire', historical_period = 'Classical India',
  dynasty = 'Gupta Dynasty', kingdom = 'Magadha', religion = 'Hinduism',
  occupation = ARRAY['Emperor']::TEXT[],
  birthplace = NULL, death_place = NULL,
  region = 'Northern India', present_state = 'Bihar', present_country = 'India',
  short_description = 'Kumaragupta I ruled the Gupta Empire from approximately 413 to 455 CE and is credited with founding Nalanda University, one of the greatest centers of learning in ancient India.',
  famous_for = 'Founding Nalanda University, one of the greatest centers of learning in ancient India. He maintained the Gupta Empire for over four decades.',
  achievements = ARRAY['Founded Nalanda University','Maintained Gupta territorial integrity from Gujarat to Bengal','Issued extensive silver and gold coinage']::TEXT[],
  notable_works = ARRAY[]::TEXT[], notable_titles = ARRAY['Mahendraditya','Maharajadhiraja']::TEXT[],
  active_start_year = 413, active_end_year = 455, century = '5th century CE', timeline_order = 10,
  father = 'Chandragupta II', mother = 'Dhruvadevi', spouse = NULL,
  children = ARRAY['Skandagupta','Purugupta']::TEXT[],
  teacher = NULL, students = NULL,
  predecessor = 'Chandragupta II', successor = 'Skandagupta',
  contemporaries = ARRAY[]::TEXT[],
  related_people = ARRAY['Chandragupta II','Skandagupta','Purugupta']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Gupta Dynasty']::TEXT[],
  related_kingdoms = ARRAY['Magadha']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Kumaragupta_I',
  keywords = ARRAY['Kumaragupta','Gupta Empire','Nalanda','university founder']::TEXT[],
  search_aliases = ARRAY['Shakraditya','Mahendraditya']::TEXT[],
  meta_description = 'Kumaragupta I (c. 413-455 CE) was a Gupta emperor who founded Nalanda University and maintained the empire for over forty years.',
  verified = TRUE, featured = FALSE, updated_at = NOW()
WHERE id = 'p15';

-- p16: Skandagupta
UPDATE personalities SET
  slug = 'skandagupta', title = 'Emperor', gender = 'Male',
  birth_year = NULL, death_year = 467, birth_text = NULL, death_text = 'c. 467 CE',
  categories = ARRAY['Ruler','Military']::TEXT[],
  civilization = 'Gupta Empire', historical_period = 'Classical India',
  dynasty = 'Gupta Dynasty', kingdom = 'Magadha', religion = 'Hinduism',
  occupation = ARRAY['Emperor']::TEXT[],
  birthplace = NULL, death_place = NULL,
  region = 'Northern India', present_state = 'Bihar', present_country = 'India',
  short_description = 'Skandagupta ruled the Gupta Empire from approximately 455 to 467 CE and is celebrated for defeating the Huna invasions as recorded in the Bhitari pillar inscription, marking the last strong phase of Gupta rule.',
  famous_for = 'Defeating the Huna (White Hun) invasions and restoring the fallen fortunes of the Gupta Empire. His Bhitari pillar inscription records these victories.',
  achievements = ARRAY['Defeated the Huna invasions','Restored Gupta power as recorded in Bhitari pillar inscription','Junagadh inscription records repair of Sudarshana Lake dam']::TEXT[],
  notable_works = ARRAY[]::TEXT[], notable_titles = ARRAY['Maharajadhiraja','Kramaditya']::TEXT[],
  active_start_year = 455, active_end_year = 467, century = '5th century CE', timeline_order = 10,
  father = 'Kumaragupta I', mother = NULL, spouse = NULL, children = NULL,
  teacher = NULL, students = NULL,
  predecessor = 'Kumaragupta I', successor = 'Purugupta',
  contemporaries = ARRAY[]::TEXT[],
  related_people = ARRAY['Kumaragupta I','Purugupta']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Gupta Dynasty']::TEXT[],
  related_kingdoms = ARRAY['Magadha']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Skandagupta',
  keywords = ARRAY['Skandagupta','Gupta Empire','Huns','Huna','Bhitari pillar']::TEXT[],
  search_aliases = ARRAY['Kramaditya']::TEXT[],
  meta_description = 'Skandagupta (c. 455-467 CE) was a Gupta emperor who defeated the Huna invasions, marking the last strong phase of Gupta rule.',
  verified = TRUE, featured = FALSE, updated_at = NOW()
WHERE id = 'p16';

-- p17: Vishnugupta
UPDATE personalities SET
  slug = 'vishnugupta', title = 'Emperor', gender = 'Male',
  birth_year = NULL, death_year = 550, birth_text = NULL, death_text = 'c. 550 CE',
  categories = ARRAY['Ruler']::TEXT[],
  civilization = 'Gupta Empire', historical_period = 'Classical India',
  dynasty = 'Gupta Dynasty', kingdom = 'Magadha', religion = 'Hinduism',
  occupation = ARRAY['Emperor']::TEXT[],
  birthplace = NULL, death_place = NULL,
  region = 'Northern India', present_state = 'Bihar', present_country = 'India',
  short_description = 'Vishnugupta was the last known ruler of the Gupta dynasty, reigning approximately from 540 to 550 CE, by which time the empire had been reduced to a small territory around Magadha.',
  famous_for = 'Being the last recognized emperor of the Gupta dynasty. His reign symbolized the final phase of the Gupta Empire decline.',
  achievements = ARRAY['Last recognized ruler of the imperial Gupta dynasty']::TEXT[],
  notable_works = ARRAY[]::TEXT[], notable_titles = ARRAY['Maharajadhiraja']::TEXT[],
  active_start_year = 540, active_end_year = 550, century = '6th century CE', timeline_order = 11,
  father = NULL, mother = NULL, spouse = NULL, children = NULL,
  teacher = NULL, students = NULL,
  predecessor = NULL, successor = NULL,
  contemporaries = ARRAY[]::TEXT[],
  related_people = ARRAY[]::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Gupta Dynasty']::TEXT[],
  related_kingdoms = ARRAY['Magadha']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Vishnugupta_(Gupta_Empire)',
  keywords = ARRAY['Vishnugupta','Gupta Empire','last Gupta ruler','decline']::TEXT[],
  search_aliases = ARRAY[]::TEXT[],
  meta_description = 'Vishnugupta (c. 540-550 CE) was the last known ruler of the Gupta dynasty, presiding over the final dissolution of imperial Gupta authority.',
  verified = TRUE, featured = FALSE, updated_at = NOW()
WHERE id = 'p17';

-- p18: Ramagupta
UPDATE personalities SET
  slug = 'ramagupta', title = 'Emperor', gender = 'Male',
  birth_year = NULL, death_year = NULL, birth_text = NULL, death_text = NULL,
  categories = ARRAY['Ruler']::TEXT[],
  civilization = 'Gupta Empire', historical_period = 'Classical India',
  dynasty = 'Gupta Dynasty', kingdom = 'Magadha', religion = 'Hinduism',
  occupation = ARRAY['Emperor']::TEXT[],
  birthplace = NULL, death_place = NULL,
  region = 'Northern India', present_state = NULL, present_country = 'India',
  short_description = 'Ramagupta was a controversial Gupta ruler believed by some historians to be the elder brother of Chandragupta II who briefly ruled between Samudragupta and Chandragupta II, known from coins and the play Devichandraguptam.',
  famous_for = 'Being a debated figure in Gupta history, possibly the elder brother of Chandragupta II who briefly usurped the throne.',
  achievements = ARRAY[]::TEXT[],
  notable_works = ARRAY[]::TEXT[], notable_titles = ARRAY['Maharajadhiraja']::TEXT[],
  active_start_year = 375, active_end_year = 380, century = '4th century CE', timeline_order = 9,
  father = 'Samudragupta', mother = 'Dattadevi', spouse = ARRAY['Dhruvadevi']::TEXT[], children = NULL,
  teacher = NULL, students = NULL,
  predecessor = 'Samudragupta', successor = 'Chandragupta II',
  contemporaries = ARRAY[]::TEXT[],
  related_people = ARRAY['Samudragupta','Chandragupta II','Dhruvadevi']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Gupta Dynasty']::TEXT[],
  related_kingdoms = ARRAY['Magadha']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Ramagupta',
  keywords = ARRAY['Ramagupta','Gupta','Devichandraguptam','disputed ruler']::TEXT[],
  search_aliases = ARRAY[]::TEXT[],
  meta_description = 'Ramagupta was a debated Gupta ruler, possibly the elder brother of Chandragupta II, known from coins and the play Devichandraguptam.',
  verified = FALSE, featured = FALSE, updated_at = NOW()
WHERE id = 'p18';

-- p19: Purugupta
UPDATE personalities SET
  slug = 'purugupta', title = 'Emperor', gender = 'Male',
  birth_year = NULL, death_year = NULL, birth_text = NULL, death_text = NULL,
  categories = ARRAY['Ruler']::TEXT[],
  civilization = 'Gupta Empire', historical_period = 'Classical India',
  dynasty = 'Gupta Dynasty', kingdom = 'Magadha', religion = 'Hinduism',
  occupation = ARRAY['Emperor']::TEXT[],
  birthplace = NULL, death_place = NULL,
  region = 'Northern India', present_state = 'Bihar', present_country = 'India',
  short_description = 'Purugupta was a Gupta emperor who ruled briefly around 467-468 CE, son of Kumaragupta I by Queen Anantadevi and half-brother of Skandagupta, marking the beginning of the gradual decline of the Gupta Empire.',
  famous_for = 'Being a Gupta emperor who succeeded Skandagupta. His reign began the gradual decline of the Gupta Empire after its peak.',
  achievements = ARRAY[]::TEXT[],
  notable_works = ARRAY[]::TEXT[], notable_titles = ARRAY['Maharajadhiraja']::TEXT[],
  active_start_year = 467, active_end_year = 468, century = '5th century CE', timeline_order = 10,
  father = 'Kumaragupta I', mother = 'Anantadevi', spouse = NULL,
  children = ARRAY['Kumaragupta II','Budhagupta']::TEXT[],
  teacher = NULL, students = NULL,
  predecessor = 'Skandagupta', successor = 'Kumaragupta II',
  contemporaries = ARRAY[]::TEXT[],
  related_people = ARRAY['Kumaragupta I','Skandagupta','Kumaragupta II']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Gupta Dynasty']::TEXT[],
  related_kingdoms = ARRAY['Magadha']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Purugupta',
  keywords = ARRAY['Purugupta','Gupta Empire','Anantadevi','decline']::TEXT[],
  search_aliases = ARRAY[]::TEXT[],
  meta_description = 'Purugupta was a Gupta emperor (c. 467-468 CE), son of Kumaragupta I, who ruled briefly after Skandagupta as the empire began its decline.',
  verified = TRUE, featured = FALSE, updated_at = NOW()
WHERE id = 'p19';

-- p23: Kanishka I
UPDATE personalities SET
  slug = 'kanishka-i', title = 'Emperor', gender = 'Male',
  birth_year = NULL, death_year = 151, birth_text = NULL, death_text = 'c. 151 CE',
  categories = ARRAY['Ruler','Patron of Buddhism']::TEXT[],
  civilization = 'Kushan Empire', historical_period = 'Ancient India',
  dynasty = 'Kushan Dynasty', kingdom = 'Kushan Empire', religion = 'Buddhism',
  occupation = ARRAY['Emperor']::TEXT[],
  birthplace = NULL, death_place = NULL,
  region = 'Central Asia and Northern India', present_state = NULL, present_country = 'India',
  short_description = 'Kanishka I was the most famous emperor of the Kushan dynasty, reigning from approximately 127 to 151 CE, who convened the Fourth Buddhist Council and promoted the spread of Mahayana Buddhism across Asia.',
  famous_for = 'Convening the Fourth Buddhist Council in Kashmir and promoting the spread of Mahayana Buddhism across Asia. His empire reached its greatest extent under his rule.',
  achievements = ARRAY['Convened the Fourth Buddhist Council in Kashmir','Promoted spread of Mahayana Buddhism to Central Asia and China','Empire extended from Central Asia to Pataliputra','Patronized Gandhara school of art','Initiated the Kanishka era (c. 78 CE)']::TEXT[],
  notable_works = ARRAY['Kanishka Stupa at Peshawar']::TEXT[],
  notable_titles = ARRAY['Kanishka the Great','Devaputra']::TEXT[],
  active_start_year = 127, active_end_year = 151, century = '2nd century CE', timeline_order = 8,
  father = 'Vima Kadphises', mother = NULL, spouse = NULL,
  children = ARRAY['Huvishka']::TEXT[],
  teacher = NULL, students = NULL,
  predecessor = 'Vima Kadphises', successor = 'Huvishka',
  contemporaries = ARRAY['Ashvaghosha','Nagarjuna','Charaka']::TEXT[],
  related_people = ARRAY['Vima Kadphises','Huvishka','Ashvaghosha']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Kushan Dynasty']::TEXT[],
  related_kingdoms = ARRAY['Kushan Empire']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Kanishka',
  keywords = ARRAY['Kanishka','Kushan Empire','Buddhism','Mahayana','Fourth Buddhist Council','Gandhara']::TEXT[],
  search_aliases = ARRAY['Kanishka the Great']::TEXT[],
  meta_description = 'Kanishka I (c. 127-151 CE) was the greatest Kushan emperor who convened the Fourth Buddhist Council and spread Mahayana Buddhism across Asia.',
  verified = TRUE, featured = TRUE, updated_at = NOW()
WHERE id = 'p23';

-- p85: Menander I
UPDATE personalities SET
  slug = 'menander-i', title = 'King', gender = 'Male',
  birth_year = NULL, death_year = -130, birth_text = NULL, death_text = 'c. 130 BCE',
  categories = ARRAY['Ruler','Patron of Buddhism']::TEXT[],
  civilization = 'Indo-Greek Kingdom', historical_period = 'Hellenistic Period',
  dynasty = 'Euthydemid', kingdom = 'Indo-Greek Kingdom', religion = 'Buddhism',
  occupation = ARRAY['King']::TEXT[],
  birthplace = NULL, death_place = NULL,
  region = 'Bactria and Northwestern India', present_state = NULL, present_country = 'Afghanistan',
  short_description = 'Menander I, known as Milinda in Indian sources, was the most celebrated Indo-Greek king who reigned from approximately 165 to 130 BCE and is famous for his philosophical dialogue with the Buddhist monk Nagasena recorded in the Milindapanha.',
  famous_for = 'His dialogue with Buddhist monk Nagasena, recorded in the Milindapanha. He is considered the most famous Indo-Greek king and a patron of Buddhism.',
  achievements = ARRAY['Extended Indo-Greek kingdom from Bactria to Punjab','Subject of the Buddhist text Milindapanha','Issued bilingual coins in Greek and Kharosthi','Patron of Buddhism as recorded in Buddhist texts']::TEXT[],
  notable_works = ARRAY[]::TEXT[], notable_titles = ARRAY['Soter','Milinda']::TEXT[],
  active_start_year = -165, active_end_year = -130, century = '2nd century BCE', timeline_order = 8,
  father = NULL, mother = NULL, spouse = ARRAY['Agathocleia']::TEXT[],
  children = ARRAY['Strato I']::TEXT[],
  teacher = NULL, students = NULL,
  predecessor = NULL, successor = 'Strato I',
  contemporaries = ARRAY['Nagasena']::TEXT[],
  related_people = ARRAY['Nagasena','Agathocleia','Strato I']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Euthydemid']::TEXT[],
  related_kingdoms = ARRAY['Indo-Greek Kingdom']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Menander_I',
  keywords = ARRAY['Menander','Indo-Greek','Milinda','Milindapanha','Nagasena','Buddhism','Bactria']::TEXT[],
  search_aliases = ARRAY['Milinda','Menander Soter']::TEXT[],
  meta_description = 'Menander I (c. 165-130 BCE), known as Milinda, was the greatest Indo-Greek king famous for the Milindapanha dialogue with the monk Nagasena.',
  verified = TRUE, featured = TRUE, updated_at = NOW()
WHERE id = 'p85';

-- p1427: Huvishka
UPDATE personalities SET
  slug = 'huvishka', title = 'Emperor', gender = 'Male',
  birth_year = NULL, death_year = 190, birth_text = NULL, death_text = 'c. 190 CE',
  categories = ARRAY['Ruler','Patron of Arts']::TEXT[],
  civilization = 'Kushan Empire', historical_period = 'Ancient India',
  dynasty = 'Kushan Dynasty', kingdom = 'Kushan Empire', religion = 'Buddhism',
  occupation = ARRAY['Emperor']::TEXT[],
  birthplace = NULL, death_place = NULL,
  region = 'Central Asia and Northern India', present_state = NULL, present_country = 'India',
  short_description = 'Huvishka was the Kushan emperor who ruled from approximately 150 to 190 CE, consolidating Kushan power in northern India during a largely peaceful reign and moving the imperial center to Mathura.',
  famous_for = 'Consolidating Kushan power in northern India during a largely peaceful reign. He moved the imperial center to Mathura and patronized diverse religious traditions.',
  achievements = ARRAY['Consolidated Kushan power in northern India','Moved imperial center to Mathura','Earliest epigraphic evidence of Buddha Amitabha','Issued extensive gold coinage depicting various deities']::TEXT[],
  notable_works = ARRAY[]::TEXT[], notable_titles = ARRAY['Devaputra']::TEXT[],
  active_start_year = 150, active_end_year = 190, century = '2nd century CE', timeline_order = 8,
  father = 'Kanishka I', mother = NULL, spouse = NULL, children = NULL,
  teacher = NULL, students = NULL,
  predecessor = 'Kanishka I', successor = 'Vasudeva I',
  contemporaries = ARRAY[]::TEXT[],
  related_people = ARRAY['Kanishka I','Vasudeva I']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Kushan Dynasty']::TEXT[],
  related_kingdoms = ARRAY['Kushan Empire']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Huvishka',
  keywords = ARRAY['Huvishka','Kushan Empire','Mathura','Amitabha','gold coinage']::TEXT[],
  search_aliases = ARRAY[]::TEXT[],
  meta_description = 'Huvishka (c. 150-190 CE) was a Kushan emperor who consolidated power in northern India, moved the capital to Mathura, and patronized diverse religions.',
  verified = TRUE, featured = FALSE, updated_at = NOW()
WHERE id = 'p1427';

-- p1428: Vasudeva I
UPDATE personalities SET
  slug = 'vasudeva-i', title = 'Emperor', gender = 'Male',
  birth_year = NULL, death_year = 225, birth_text = NULL, death_text = 'c. 225 CE',
  categories = ARRAY['Ruler']::TEXT[],
  civilization = 'Kushan Empire', historical_period = 'Ancient India',
  dynasty = 'Kushan Dynasty', kingdom = 'Kushan Empire', religion = 'Hinduism',
  occupation = ARRAY['Emperor']::TEXT[],
  birthplace = NULL, death_place = NULL,
  region = 'Central Asia and Northern India', present_state = NULL, present_country = 'India',
  short_description = 'Vasudeva I was the last of the Great Kushan emperors, ruling from approximately 190 to 225 CE, whose reign marked the transition toward Hinduism in Kushan religious patronage and the beginning of Kushan decline.',
  famous_for = 'Being the last of the Great Kushans. His reign marked a shift toward Hindu religious patronage and the beginning of Kushan decline.',
  achievements = ARRAY['Last of the Great Kushan emperors','Shifted religious patronage toward Hinduism (Shiva worship)']::TEXT[],
  notable_works = ARRAY[]::TEXT[], notable_titles = ARRAY['Devaputra','Maharaja']::TEXT[],
  active_start_year = 190, active_end_year = 225, century = '2nd-3rd century CE', timeline_order = 9,
  father = NULL, mother = NULL, spouse = NULL, children = NULL,
  teacher = NULL, students = NULL,
  predecessor = 'Huvishka', successor = 'Kanishka II',
  contemporaries = ARRAY[]::TEXT[],
  related_people = ARRAY['Huvishka','Kanishka II']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Kushan Dynasty']::TEXT[],
  related_kingdoms = ARRAY['Kushan Empire']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Vasudeva_I',
  keywords = ARRAY['Vasudeva','Kushan Empire','last great Kushan','Hinduism','Shiva','decline']::TEXT[],
  search_aliases = ARRAY['Bazodeo']::TEXT[],
  meta_description = 'Vasudeva I (c. 190-225 CE) was the last Great Kushan emperor who shifted religious patronage toward Hinduism before the empire began to fragment.',
  verified = TRUE, featured = FALSE, updated_at = NOW()
WHERE id = 'p1428';

-- p1435: Vima Kadphises
UPDATE personalities SET
  slug = 'vima-kadphises', title = 'Emperor', gender = 'Male',
  birth_year = NULL, death_year = 127, birth_text = NULL, death_text = 'c. 127 CE',
  categories = ARRAY['Ruler','Economic Reformer']::TEXT[],
  civilization = 'Kushan Empire', historical_period = 'Ancient India',
  dynasty = 'Kushan Dynasty', kingdom = 'Kushan Empire', religion = 'Hinduism',
  occupation = ARRAY['Emperor']::TEXT[],
  birthplace = NULL, death_place = NULL,
  region = 'Central Asia and Northern India', present_state = NULL, present_country = 'Afghanistan',
  short_description = 'Vima Kadphises was a Kushan ruler who reigned from approximately 113 to 127 CE and was the first Kushan king to introduce gold coinage, reforming the monetary system and consolidating control over Silk Road trade routes.',
  famous_for = 'Being the first Kushan ruler to issue gold coins, marking a significant step in Kushan economic development. He controlled key Silk Road trade routes.',
  achievements = ARRAY['First Kushan ruler to introduce gold coinage','Reformed the Kushan monetary system','Consolidated control over Silk Road trade routes']::TEXT[],
  notable_works = ARRAY[]::TEXT[], notable_titles = ARRAY['Maharaja','Devaputra']::TEXT[],
  active_start_year = 113, active_end_year = 127, century = '1st-2nd century CE', timeline_order = 8,
  father = 'Vima Takto', mother = NULL, spouse = NULL,
  children = ARRAY['Kanishka I']::TEXT[],
  teacher = NULL, students = NULL,
  predecessor = 'Vima Takto', successor = 'Kanishka I',
  contemporaries = ARRAY[]::TEXT[],
  related_people = ARRAY['Vima Takto','Kanishka I','Kujula Kadphises']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Kushan Dynasty']::TEXT[],
  related_kingdoms = ARRAY['Kushan Empire']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Vima_Kadphises',
  keywords = ARRAY['Vima Kadphises','Kushan Empire','gold coinage','Silk Road','trade']::TEXT[],
  search_aliases = ARRAY[]::TEXT[],
  meta_description = 'Vima Kadphises (c. 113-127 CE) was a Kushan ruler who first introduced gold coinage and controlled key Silk Road trade routes.',
  verified = TRUE, featured = FALSE, updated_at = NOW()
WHERE id = 'p1435';

-- p1436: Kujula Kadphises
UPDATE personalities SET
  slug = 'kujula-kadphises', title = 'Emperor', gender = 'Male',
  birth_year = NULL, death_year = 85, birth_text = NULL, death_text = 'c. 85 CE',
  categories = ARRAY['Ruler','Founder']::TEXT[],
  civilization = 'Kushan Empire', historical_period = 'Ancient India',
  dynasty = 'Kushan Dynasty', kingdom = 'Kushan Empire', religion = NULL,
  occupation = ARRAY['Emperor']::TEXT[],
  birthplace = NULL, death_place = NULL,
  region = 'Bactria and Northwestern India', present_state = NULL, present_country = 'Afghanistan',
  short_description = 'Kujula Kadphises was the founder of the Kushan dynasty who unified the five Yuezhi principalities and established the Kushan Empire by conquering Bactria, Gandhara, and parts of northwestern India during the first century CE.',
  famous_for = 'Founding the Kushan Empire by unifying the five Yuezhi tribes and conquering Bactria and Gandhara.',
  achievements = ARRAY['Founded the Kushan dynasty','Unified the five Yuezhi principalities','Conquered Bactria and Gandhara','Established Kushan control over northwestern India','Issued bilingual coins in Greek and Kharosthi']::TEXT[],
  notable_works = ARRAY[]::TEXT[], notable_titles = ARRAY['Maharaja','Devaputra']::TEXT[],
  active_start_year = 30, active_end_year = 85, century = '1st century CE', timeline_order = 8,
  father = NULL, mother = NULL, spouse = NULL,
  children = ARRAY['Vima Takto']::TEXT[],
  teacher = NULL, students = NULL,
  predecessor = NULL, successor = 'Vima Takto',
  contemporaries = ARRAY[]::TEXT[],
  related_people = ARRAY['Vima Takto','Vima Kadphises']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Kushan Dynasty']::TEXT[],
  related_kingdoms = ARRAY['Kushan Empire']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Kujula_Kadphises',
  keywords = ARRAY['Kujula Kadphises','Kushan Empire','founder','Yuezhi','Bactria','Gandhara']::TEXT[],
  search_aliases = ARRAY['Kadphises I']::TEXT[],
  meta_description = 'Kujula Kadphises (c. 30-85 CE) was the founder of the Kushan dynasty who unified the Yuezhi tribes and conquered Bactria and Gandhara.',
  verified = TRUE, featured = FALSE, updated_at = NOW()
WHERE id = 'p1436';

-- p20: Harshavardhana
UPDATE personalities SET
  slug = 'harshavardhana', title = 'Emperor', gender = 'Male',
  birth_year = 590, death_year = 647, birth_text = 'c. 590 CE', death_text = 'c. 647 CE',
  categories = ARRAY['Ruler','Patron of Arts','Author']::TEXT[],
  civilization = 'Vardhana Dynasty', historical_period = 'Early Medieval India',
  dynasty = 'Vardhana (Pushyabhuti)', kingdom = 'Kannauj', religion = 'Buddhism',
  occupation = ARRAY['Emperor','Author']::TEXT[],
  birthplace = 'Thanesar', death_place = NULL,
  region = 'Northern India', present_state = 'Haryana', present_country = 'India',
  short_description = 'Harshavardhana was the emperor of Kannauj from 606 to 647 CE who unified much of northern India from Punjab to Bengal and was a great patron of literature, arts, and Buddhism, hosting the Chinese pilgrim Xuanzang at his court.',
  famous_for = 'Unifying northern India and being a great patron of literature and Buddhism. His court was adorned by scholars like Banabhatta, and he hosted the Chinese pilgrim Xuanzang.',
  achievements = ARRAY['Unified northern India from Punjab to Bengal','Patron of literature and arts','Hosted Chinese pilgrim Xuanzang at his court','Authored three Sanskrit plays: Ratnavali, Priyadarshika, and Nagananda','Held the Kannauj assembly to promote Buddhism']::TEXT[],
  notable_works = ARRAY['Ratnavali','Priyadarshika','Nagananda']::TEXT[],
  notable_titles = ARRAY['Shiladitya','Maharajadhiraja']::TEXT[],
  active_start_year = 606, active_end_year = 647, century = '7th century CE', timeline_order = 12,
  father = 'Prabhakaravardhana', mother = 'Yashovati', spouse = NULL, children = NULL,
  teacher = NULL, students = NULL,
  predecessor = 'Rajyavardhana', successor = NULL,
  contemporaries = ARRAY['Banabhatta','Xuanzang','Pulakeshin II','Bhaskaravarman']::TEXT[],
  related_people = ARRAY['Prabhakaravardhana','Rajyavardhana','Banabhatta','Xuanzang','Pulakeshin II']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Vardhana']::TEXT[],
  related_kingdoms = ARRAY['Kannauj']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Harsha',
  keywords = ARRAY['Harshavardhana','Harsha','Kannauj','Vardhana','Buddhism','Xuanzang','Banabhatta']::TEXT[],
  search_aliases = ARRAY['Harsha','Shiladitya']::TEXT[],
  meta_description = 'Harshavardhana (590-647 CE) was emperor of Kannauj who unified northern India and patronized literature, arts, and Buddhism.',
  verified = TRUE, featured = TRUE, updated_at = NOW()
WHERE id = 'p20';

-- p21: Shashanka
UPDATE personalities SET
  slug = 'shashanka', title = 'King', gender = 'Male',
  birth_year = NULL, death_year = 637, birth_text = NULL, death_text = 'c. 637 CE',
  categories = ARRAY['Ruler']::TEXT[],
  civilization = 'Gauda Kingdom', historical_period = 'Early Medieval India',
  dynasty = NULL, kingdom = 'Gauda', religion = 'Hinduism',
  occupation = ARRAY['King']::TEXT[],
  birthplace = NULL, death_place = NULL,
  region = 'Bengal', present_state = 'West Bengal', present_country = 'India',
  short_description = 'Shashanka was the first independent king of the Gauda Kingdom in Bengal, reigning from approximately 590 to 637 CE, who was a major rival of Harshavardhana and is credited with creating the Bengali calendar.',
  famous_for = 'Being the first independent king of Bengal and a fierce rival of Harshavardhana. He is credited with creating the Bengali calendar and unifying Bengal.',
  achievements = ARRAY['First independent king of the Gauda Kingdom in Bengal','Unified much of Bengal under a single ruler','Credited with creating the Bengali calendar','Established capital at Karnasuvarna']::TEXT[],
  notable_works = ARRAY[]::TEXT[], notable_titles = ARRAY['Maharaja','Gaudadhipa']::TEXT[],
  active_start_year = 590, active_end_year = 637, century = '7th century CE', timeline_order = 12,
  father = NULL, mother = NULL, spouse = NULL, children = NULL,
  teacher = NULL, students = NULL,
  predecessor = NULL, successor = NULL,
  contemporaries = ARRAY['Harshavardhana','Bhaskaravarman']::TEXT[],
  related_people = ARRAY['Harshavardhana','Rajyavardhana','Bhaskaravarman']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY[]::TEXT[],
  related_kingdoms = ARRAY['Gauda']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Shashanka',
  keywords = ARRAY['Shashanka','Gauda','Bengal','Harsha rival','Bengali calendar','Karnasuvarna']::TEXT[],
  search_aliases = ARRAY['Sasanka']::TEXT[],
  meta_description = 'Shashanka (c. 590-637 CE) was the first independent king of Gauda in Bengal, a rival of Harshavardhana credited with creating the Bengali calendar.',
  verified = TRUE, featured = FALSE, updated_at = NOW()
WHERE id = 'p21';

-- p22: Bhaskaravarman
UPDATE personalities SET
  slug = 'bhaskaravarman', title = 'King', gender = 'Male',
  birth_year = NULL, death_year = 650, birth_text = NULL, death_text = 'c. 650 CE',
  categories = ARRAY['Ruler']::TEXT[],
  civilization = 'Kamarupa Kingdom', historical_period = 'Early Medieval India',
  dynasty = 'Varman Dynasty', kingdom = 'Kamarupa', religion = 'Hinduism',
  occupation = ARRAY['King']::TEXT[],
  birthplace = NULL, death_place = NULL,
  region = 'Assam', present_state = 'Assam', present_country = 'India',
  short_description = 'Bhaskaravarman was the last and greatest king of the Varman dynasty of Kamarupa, ruling from approximately 594 to 650 CE, who was a close ally of Harshavardhana and hosted the Chinese pilgrim Xuanzang at his court.',
  famous_for = 'Being the greatest king of the Varman dynasty of Kamarupa and a key ally of Harshavardhana. He hosted the Chinese pilgrim Xuanzang at his court.',
  achievements = ARRAY['Last and greatest king of the Varman dynasty of Kamarupa','Ally of Harshavardhana against Shashanka of Gauda','Hosted Chinese pilgrim Xuanzang','Known as Kumar Raja for his scholarly pursuits']::TEXT[],
  notable_works = ARRAY[]::TEXT[], notable_titles = ARRAY['Maharaja','Kumar Raja']::TEXT[],
  active_start_year = 594, active_end_year = 650, century = '7th century CE', timeline_order = 12,
  father = 'Susthitavarman', mother = NULL, spouse = NULL, children = NULL,
  teacher = NULL, students = NULL,
  predecessor = 'Susthitavarman', successor = NULL,
  contemporaries = ARRAY['Harshavardhana','Shashanka','Xuanzang']::TEXT[],
  related_people = ARRAY['Harshavardhana','Shashanka','Xuanzang','Susthitavarman']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Varman Dynasty']::TEXT[],
  related_kingdoms = ARRAY['Kamarupa']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Bhaskaravarman',
  keywords = ARRAY['Bhaskaravarman','Kamarupa','Assam','Varman dynasty','Harsha ally','Kumar Raja','Xuanzang']::TEXT[],
  search_aliases = ARRAY['Kumar Raja']::TEXT[],
  meta_description = 'Bhaskaravarman (c. 594-650 CE) was the greatest king of the Varman dynasty of Kamarupa, Assam, and a key ally of Harshavardhana.',
  verified = TRUE, featured = FALSE, updated_at = NOW()
WHERE id = 'p22';
