/*
# Insert unique dynasty rows

1. Deduplicated all 4 pasted tables by unique id (first occurrence kept)
2. 178 unique dynasty/kingdom rows inserted via upsert (ON CONFLICT DO UPDATE)
3. Existing 6 rows (maurya, gupta, chola, mughal, bhonsle, sangama) updated with richer data
4. No data loss - all existing rows preserved or updated
5. Every id is guaranteed unique - no duplicates
*/

INSERT INTO dynasties (id, name, period, founder, capital, civilization_id) VALUES
  ('indus', 'Indus Valley Civilization', '3300 - 1300 BCE', 'Unknown', 'Harappa, Mohenjo-Daro, Lothal', 'indus'),
  ('vedic', 'Early Vedic Tribes', '1500 - 600 BCE', 'Various Rishis & Chiefs', 'No fixed capital', 'vedic'),
  ('magadha', 'Magadha Kingdom', '600 - 321 BCE', 'Bimbisara', 'Rajagriha, Pataliputra', 'mahajanapada'),
  ('kosala', 'Kosala Kingdom', '600 - 300 BCE', 'King Prasenajit', 'Shravasti', 'mahajanapada'),
  ('vatsa', 'Vatsa Kingdom', '600 - 300 BCE', 'Udayana', 'Kaushambi', 'mahajanapada'),
  ('avanti', 'Avanti Kingdom', '600 - 300 BCE', 'Pradyota', 'Ujjain', 'mahajanapada'),
  ('maurya', 'Maurya Empire', '321 - 185 BCE', 'Chandragupta Maurya', 'Pataliputra', 'mauryan'),
  ('shunga', 'Shunga Empire', '185 - 73 BCE', 'Pushyamitra Shunga', 'Pataliputra', 'shunga'),
  ('kanva', 'Kanva Dynasty', '73 - 26 BCE', 'Vasudeva Kanva', 'Pataliputra', 'kanva'),
  ('satavahana', 'Satavahana Dynasty', '230 BCE - 220 CE', 'Simuka', 'Pratishthana (Paithan)', 'satavahana'),
  ('indo-greek', 'Indo-Greek Kingdom', '180 BCE - 10 CE', 'Demetrius I', 'Taxila, Sagala', 'indo-greek'),
  ('kushan', 'Kushan Empire', '30 - 375 CE', 'Kujula Kadphises', 'Purushapura (Peshawar)', 'kushan'),
  ('gupta', 'Gupta Empire', '320 - 550 CE', 'Sri Gupta', 'Pataliputra', 'gupta'),
  ('vakataka', 'Vakataka Dynasty', '250 - 500 CE', 'Vindhyashakti', 'Nandivardhana', 'vakataka'),
  ('harsha', 'Pushyabhuti Dynasty', '606 - 647 CE', 'Harshavardhana', 'Kannauj', 'harsha'),
  ('pallava', 'Pallava Dynasty', '275 - 897 CE', 'Simhavarman', 'Kanchipuram', 'pallava'),
  ('chalukya', 'Badami Chalukya', '543 - 753 CE', 'Pulakeshin I', 'Badami', 'chalukya'),
  ('rashtrakuta', 'Rashtrakuta Dynasty', '753 - 982 CE', 'Dantidurga', 'Manyakheta', 'rashtrakuta'),
  ('chola', 'Chola Empire', '848 - 1279 CE', 'Vijayalaya', 'Thanjavur, Gangaikonda Cholapuram', 'chola'),
  ('chera', 'Chera Dynasty', '600 BCE - 1124 CE', 'Uthiyan Cheralathan', 'Karur, Vanchi', 'chera'),
  ('pandya', 'Pandya Dynasty', '600 BCE - 1650 CE', 'Nedunjeliyan', 'Madurai', 'pandya'),
  ('hoysala', 'Hoysala Empire', '1022 - 1343 CE', 'Sala', 'Halebidu, Belur', 'hoysala'),
  ('kakatiya', 'Kakatiya Dynasty', '1163 - 1323 CE', 'Rudradeva', 'Orugallu (Warangal)', 'kakatiya'),
  ('vijayanagara', 'Vijayanagara Empire', '1336 - 1646 CE', 'Harihara I & Bukka Raya I', 'Vijayanagara (Hampi)', 'vijayanagara'),
  ('pratihara', 'Gurjara-Pratihara', '730 - 1036 CE', 'Nagabhata I', 'Kannauj', 'pratihara'),
  ('pala', 'Pala Empire', '750 - 1174 CE', 'Gopala I', 'Pataliputra, Vikramashila', 'pala'),
  ('paramara', 'Paramara Dynasty', '800 - 1305 CE', 'Upendra', 'Dhara', 'paramara'),
  ('chandela', 'Chandela Dynasty', '831 - 1315 CE', 'Nannuka', 'Khajuraho', 'chandela'),
  ('kalachuri', 'Kalachuri Dynasty', '550 - 1200 CE', 'Kokalla I', 'Tripuri', 'kalachuri'),
  ('eastern-ganga', 'Eastern Ganga Dynasty', '498 - 1434 CE', 'Anantavarman Chodaganga', 'Kalinganagara', 'eastern-ganga'),
  ('delhi-sultanate', 'Delhi Sultanate', '1206 - 1526 CE', 'Qutb-ud-din Aibak', 'Delhi', 'delhi-sultanate'),
  ('mughal', 'Mughal Empire', '1526 - 1857 CE', 'Babur', 'Agra, Delhi', 'mughal'),
  ('maratha', 'Maratha Empire', '1674 - 1818 CE', 'Shivaji Maharaj', 'Raigad, Satara, Pune', 'maratha'),
  ('sikh', 'Sikh Empire', '1799 - 1849 CE', 'Maharaja Ranjit Singh', 'Lahore', 'sikh'),
  ('ahom', 'Ahom Kingdom', '1228 - 1826 CE', 'Sukaphaa', 'Rangpur, Jorhat', 'ahom'),
  ('mysore', 'Kingdom of Mysore', '1399 - 1799 CE', 'Yaduraya Wodeyar', 'Mysore', 'mysore'),
  ('travancore', 'Kingdom of Travancore', '1729 - 1949 CE', 'Marthanda Varma', 'Thiruvananthapuram', 'travancore'),
  ('cochin', 'Kingdom of Cochin', '1102 - 1949 CE', 'Various Perumals', 'Kochi', 'cochin'),
  ('rajputana', 'Rajput States', '700 - 1947 CE', 'Various Rajput Clans', 'Udaipur, Jodhpur, Jaipur', 'rajput'),
  ('haryanka', 'Haryanka Dynasty', '544 - 412 BCE', 'Bimbisara', 'Rajagriha', 'mahajanapada'),
  ('shishunaga', 'Shishunaga Dynasty', '412 - 345 BCE', 'Shishunaga', 'Rajagriha, Pataliputra', 'mahajanapada'),
  ('nanda', 'Nanda Dynasty', '345 - 321 BCE', 'Mahapadma Nanda', 'Pataliputra', 'nanda'),
  ('ikshvaku', 'Ikshvaku Dynasty', '200 BCE - 300 CE', 'Ikshvaku', 'Pratishthana', 'ikshvaku'),
  ('abhira', 'Abhira Kingdom', '203 - 370 CE', 'Abhira Kings', 'Nasik, Paithan', 'abhira'),
  ('western-kshatrapa', 'Western Kshatrapa', '35 - 405 CE', 'Nahapana', 'Ujjain, Barygaza', 'kshatrapa'),
  ('maitraka', 'Maitraka Dynasty', '475 - 776 CE', 'Bhatarka', 'Vallabhi', 'maitraka'),
  ('pushyabhuti', 'Pushyabhuti Dynasty', '606 - 647 CE', 'Prabhakaravardhana', 'Thanesar, Kannauj', 'pushyabhuti'),
  ('ganga', 'Western Ganga Dynasty', '350 - 1000 CE', 'Konganivarman', 'Talakadu', 'ganga'),
  ('kadamba', 'Kadamba Dynasty', '345 - 525 CE', 'Mayurasharma', 'Banavasi', 'kadamba'),
  ('chera-perumal', 'Chera Perumals of Makotai', '800 - 1124 CE', 'Cheraman Perumal', 'Kodungallur', 'chera'),
  ('eastern-chalukya', 'Eastern Chalukya', '624 - 1070 CE', 'Kubja Vishnuvardhana', 'Vengi', 'chalukya'),
  ('kalyani-chalukya', 'Kalyani Chalukya', '973 - 1189 CE', 'Tailapa II', 'Kalyani', 'chalukya'),
  ('yadava', 'Seuna Yadava Dynasty', '1187 - 1317 CE', 'Bhillama V', 'Devagiri', 'yadava'),
  ('reddy', 'Reddy Kingdom', '1325 - 1448 CE', 'Prolaya Vema Reddy', 'Kondavidu', 'reddy'),
  ('bahmani', 'Bahmani Sultanate', '1347 - 1527 CE', 'Ala-ud-Din Bahman Shah', 'Gulbarga, Bidar', 'bahmani'),
  ('deccan-sultanates', 'Deccan Sultanates', '1490 - 1687 CE', 'Various', 'Ahmednagar, Bijapur, Golconda', 'deccan'),
  ('koch', 'Koch Kingdom', '1515 - 1949 CE', 'Biswa Singha', 'Cooch Behar', 'koch'),
  ('kamarupa', 'Kamarupa Kingdom', '350 - 1140 CE', 'Pushyavarman', 'Pragjyotishpura', 'kamarupa'),
  ('twipra', 'Twipra Kingdom', '1460 - 1949 CE', 'Ratna Manikya', 'Udaipur (Tripura)', 'twipra'),
  ('jaintia', 'Jaintia Kingdom', '525 - 1835 CE', 'Various Kings', 'Jaintiapur', 'jaintia'),
  ('kachari', 'Kachari Kingdom', '12th century - 1832 CE', 'Various Kings', 'Khaspur, Maibong', 'kachari'),
  ('manipur', 'Manipur Kingdom', '33 CE - 1949 CE', 'Nongda Lairen Pakhangba', 'Imphal', 'manipur'),
  ('kashmir', 'Kashmir Sultanate', '1339 - 1586 CE', 'Shah Mir', 'Srinagar', 'kashmir'),
  ('ladakh', 'Kingdom of Ladakh', '10th century - 1842 CE', 'Nyimagon', 'Leh', 'ladakh'),
  ('guge', 'Guge Kingdom', '10th - 17th century', 'Nyimagon', 'Tsaparang', 'guge'),
  ('bundela', 'Bundela Kingdom', '14th - 18th century', 'Hemkaran', 'Orchha', 'bundela'),
  ('baghel', 'Baghel Kingdom', '14th - 19th century', 'Various', 'Rewa', 'baghel'),
  ('gond', 'Gond Kingdoms', '14th - 18th century', 'Various Gond Kings', 'Chanda, Garha, Mandla', 'gond'),
  ('bhonsle', 'Bhonsle Dynasty', '1674 - 1818 CE', 'Shivaji Maharaj', 'Raigad, Satara', 'maratha'),
  ('gaekwad', 'Gaekwad Dynasty', '1721 - 1948 CE', 'Pilaji Rao Gaekwad', 'Baroda', 'maratha'),
  ('holkar', 'Holkar Dynasty', '1728 - 1948 CE', 'Malhar Rao Holkar', 'Indore', 'maratha'),
  ('scindia', 'Scindia Dynasty', '1726 - 1948 CE', 'Ranoji Scindia', 'Gwalior', 'maratha'),
  ('peshwa', 'Peshwa Dynasty', '1713 - 1818 CE', 'Balaji Vishwanath', 'Pune', 'maratha'),
  ('rohilla', 'Rohilla Kingdom', '1707 - 1774 CE', 'Ali Mohammed Khan', 'Bareilly', 'rohilla'),
  ('awadh', 'Kingdom of Awadh', '1722 - 1856 CE', 'Saadat Khan', 'Lucknow', 'awadh'),
  ('hyderabad', 'Nizam of Hyderabad', '1724 - 1948 CE', 'Asaf Jah I', 'Hyderabad', 'nizam'),
  ('arcot', 'Nawabs of Arcot', '1692 - 1801 CE', 'Zulfikar Ali Khan', 'Arcot', 'nawab'),
  ('bengal', 'Nawabs of Bengal', '1717 - 1880 CE', 'Murshid Quli Khan', 'Murshidabad', 'nawab'),
  ('carnatic', 'Nawabs of Carnatic', '1692 - 1801 CE', 'Various', 'Arcot', 'nawab'),
  ('junagadh', 'Junagadh State', '1730 - 1948 CE', 'Various Nawabs', 'Junagadh', 'princely'),
  ('jodhpur', 'Marwar Kingdom', '13th century - 1949 CE', 'Rao Jodha', 'Jodhpur', 'rajput'),
  ('udaipur', 'Mewar Kingdom', '734 - 1949 CE', 'Bappa Rawal', 'Udaipur', 'rajput'),
  ('jaipur', 'Amber Kingdom', '1036 - 1949 CE', 'Duleh Rai', 'Jaipur', 'rajput'),
  ('bikaner', 'Bikaner State', '1465 - 1949 CE', 'Rao Bika', 'Bikaner', 'rajput'),
  ('kota', 'Kota State', '1631 - 1949 CE', 'Madho Singh', 'Kota', 'rajput'),
  ('bundi', 'Bundi State', '1342 - 1949 CE', 'Rao Deva', 'Bundi', 'rajput'),
  ('alwar', 'Alwar State', '1770 - 1949 CE', 'Pratap Singh', 'Alwar', 'rajput'),
  ('bharatpur', 'Bharatpur State', '1722 - 1949 CE', 'Badan Singh', 'Bharatpur', 'jats'),
  ('dholpur', 'Dholpur State', '1806 - 1949 CE', 'Various', 'Dholpur', 'rajput'),
  ('karauli', 'Karauli State', '1348 - 1949 CE', 'Various', 'Karauli', 'rajput'),
  ('sirohi', 'Sirohi State', '1311 - 1949 CE', 'Various', 'Sirohi', 'rajput'),
  ('dungarpur', 'Dungarpur State', '14th century - 1949 CE', 'Various', 'Dungarpur', 'rajput'),
  ('pratapgarh', 'Pratapgarh State', '1422 - 1949 CE', 'Various', 'Pratapgarh', 'rajput'),
  ('kishangarh', 'Kishangarh State', '1609 - 1949 CE', 'Various', 'Kishangarh', 'rajput'),
  ('tonk', 'Tonk State', '1806 - 1949 CE', 'Various', 'Tonk', 'nawab'),
  ('bhopal', 'Bhopal State', '1723 - 1949 CE', 'Dost Mohammad Khan', 'Bhopal', 'bhopal'),
  ('indore', 'Holkar State', '1728 - 1948 CE', 'Malhar Rao Holkar', 'Indore', 'maratha'),
  ('gwalior', 'Scindia State', '1726 - 1948 CE', 'Ranoji Scindia', 'Gwalior', 'maratha'),
  ('baroda', 'Gaekwad State', '1721 - 1948 CE', 'Pilaji Rao Gaekwad', 'Baroda', 'maratha'),
  ('kolhapur', 'Kolhapur State', '1710 - 1949 CE', 'Tarabai', 'Kolhapur', 'maratha'),
  ('satara', 'Satara State', '1818 - 1848 CE', 'Pratap Singh', 'Satara', 'maratha'),
  ('pudukkottai', 'Pudukkottai State', '1680 - 1948 CE', 'Raghunatha Raya Tondaiman', 'Pudukkottai', 'pudukkottai'),
  ('ramnad', 'Ramnad Kingdom', '1605 - 1948 CE', 'Various Setupatis', 'Ramanathapuram', 'setupati'),
  ('lichchhavi', 'Lichchhavi Republic', '600 - 300 BCE', 'Various', 'Vaishali', 'mahajanapada'),
  ('videha', 'Videha Kingdom', '600 - 300 BCE', 'Janaka', 'Mithila', 'mahajanapada'),
  ('malla', 'Malla Republic', '600 - 300 BCE', 'Various', 'Kusinara, Pava', 'mahajanapada'),
  ('vajji', 'Vajji Confederation', '600 - 300 BCE', 'Various', 'Vaishali', 'mahajanapada'),
  ('kuru', 'Kuru Kingdom', '1200 - 500 BCE', 'Various', 'Hastinapura', 'vedic'),
  ('panchala', 'Panchala Kingdom', '600 - 300 BCE', 'Various', 'Ahichchhatra', 'mahajanapada'),
  ('matsya', 'Matsya Kingdom', '600 - 300 BCE', 'Various', 'Viratanagara', 'mahajanapada'),
  ('surasena', 'Surasena Kingdom', '600 - 300 BCE', 'Various', 'Mathura', 'mahajanapada'),
  ('chedi', 'Chedi Kingdom', '600 - 300 BCE', 'Shishupala', 'Suktimati', 'mahajanapada'),
  ('kalinga', 'Kalinga Kingdom', '600 BCE - 300 CE', 'Various', 'Tosali', 'kalinga'),
  ('andhra', 'Andhra Kingdom', '300 BCE - 300 CE', 'Various', 'Pratishthana', 'andhra'),
  ('naga', 'Naga Dynasty', '200 - 400 CE', 'Various', 'Padmavati', 'naga'),
  ('gana', 'Gana Sanghas', '600 - 300 BCE', 'Various', 'Various', 'gana'),
  ('kuninda', 'Kuninda Kingdom', '300 BCE - 300 CE', 'Amoghbhuti', 'Various', 'kuninda'),
  ('trigarta', 'Trigarta Kingdom', '600 BCE - 1000 CE', 'Various', 'Jalandhar', 'trigarta'),
  ('audumbara', 'Audumbara Republic', '300 BCE - 100 CE', 'Various', 'Pathankot', 'audumbara'),
  ('yaudheya', 'Yaudheya Republic', '300 BCE - 400 CE', 'Various', 'Bahalgarh', 'yaudheya'),
  ('malava', 'Malava Republic', '300 BCE - 400 CE', 'Various', 'Ujjain', 'malava'),
  ('arjunayana', 'Arjunayana Republic', '300 BCE - 300 CE', 'Various', 'Various', 'arjunayana'),
  ('western-satrap', 'Western Satraps', '35 - 405 CE', 'Nahapana', 'Ujjain', 'kshatrapa'),
  ('valabhi', 'Valabhi Kingdom', '475 - 776 CE', 'Bhatarka', 'Vallabhi', 'maitraka'),
  ('gurjara', 'Gurjara Kingdom', '500 - 800 CE', 'Various', 'Various', 'gurjara'),
  ('shailodbhava', 'Shailodbhava Dynasty', '550 - 736 CE', 'Various', 'Kongoda', 'shailodbhava'),
  ('bhauma-kara', 'Bhauma-Kara Dynasty', '736 - 940 CE', 'Various', 'Jajpur', 'bhauma'),
  ('somavamshi', 'Somavamshi Dynasty', '900 - 1110 CE', 'Various', 'Jajpur', 'somavamshi'),
  ('haihaya', 'Haihaya Dynasty', '600 - 1200 CE', 'Various', 'Various', 'haihaya'),
  ('tomara', 'Tomara Dynasty', '736 - 1160 CE', 'Anangapal', 'Delhi', 'tomara'),
  ('chauhan', 'Chauhan Dynasty', '700 - 1300 CE', 'Various', 'Ajmer, Delhi', 'chauhan'),
  ('solanki', 'Solanki Dynasty', '942 - 1244 CE', 'Mularaja I', 'Anhilwad Patan', 'solanki'),
  ('vaghela', 'Vaghela Dynasty', '1244 - 1304 CE', 'Visaladeva', 'Dholka', 'vaghela'),
  ('chaulukya', 'Chaulukya of Gujarat', '942 - 1244 CE', 'Mularaja I', 'Anhilwad Patan', 'chaulukya'),
  ('nizamshahi', 'Nizam Shahi Dynasty', '1490 - 1636 CE', 'Malik Ahmad', 'Ahmednagar', 'deccan'),
  ('adilshahi', 'Adil Shahi Dynasty', '1490 - 1686 CE', 'Yusuf Adil Shah', 'Bijapur', 'deccan'),
  ('qutbshahi', 'Qutb Shahi Dynasty', '1518 - 1687 CE', 'Sultan Quli Qutb Shah', 'Golconda', 'deccan'),
  ('baridshahi', 'Barid Shahi Dynasty', '1492 - 1619 CE', 'Amir Barid I', 'Bidar', 'deccan'),
  ('imadshahi', 'Imad Shahi Dynasty', '1490 - 1572 CE', 'Fathullah Imad-ul-Mulk', 'Berar', 'deccan'),
  ('faruqi', 'Faruqi Dynasty', '1382 - 1601 CE', 'Various', 'Burhanpur', 'faruqi'),
  ('sharqi', 'Sharqi Dynasty', '1394 - 1479 CE', 'Malik Sarwar', 'Jaunpur', 'sharqi'),
  ('sur', 'Sur Dynasty', '1540 - 1555 CE', 'Sher Shah Suri', 'Delhi', 'sur'),
  ('karrani', 'Karrani Dynasty', '1564 - 1576 CE', 'Sulaiman Khan Karrani', 'Tandah', 'bengal'),
  ('hussaini', 'Hussain Shahi Dynasty', '1494 - 1538 CE', 'Alauddin Hussain Shah', 'Gaur', 'bengal'),
  ('ilyas', 'Ilyas Shahi Dynasty', '1342 - 1487 CE', 'Shamsuddin Ilyas Shah', 'Gaur', 'bengal'),
  ('habshi', 'Habshi Dynasty', '1487 - 1494 CE', 'Various', 'Gaur', 'bengal'),
  ('sena', 'Sena Dynasty', '1097 - 1260 CE', 'Vijaya Sena', 'Nadia', 'sena'),
  ('kharavela', 'Mahameghavahana', '193 - 170 BCE', 'Kharavela', 'Kalinganagara', 'kalinga'),
  ('mathara', 'Mathara Dynasty', '4th - 6th century CE', 'Various', 'Various', 'kalinga'),
  ('tunga', 'Tunga Dynasty', '11th century CE', 'Various', 'Various', 'odisha'),
  ('suryavamshi', 'Suryavamshi Gajapati', '1434 - 1541 CE', 'Kapilendra Deva', 'Cuttack', 'gajapati'),
  ('bhoi', 'Bhoi Dynasty', '1541 - 1560 CE', 'Govinda Vidyadhara', 'Cuttack', 'bhoi'),
  ('musunuri', 'Musunuri Nayaks', '1336 - 1368 CE', 'Various', 'Various', 'musunuri'),
  ('velama', 'Velama Dynasty', '1325 - 1475 CE', 'Various', 'Rachakonda', 'velama'),
  ('nayaka', 'Madurai Nayak', '1529 - 1736 CE', 'Various', 'Madurai', 'nayaka'),
  ('wodeyar', 'Wodeyar Dynasty', '1399 - 1950 CE', 'Yaduraya', 'Mysore', 'wodeyar'),
  ('keladi', 'Keladi Nayaka', '1499 - 1763 CE', 'Various', 'Ikkeri', 'keladi'),
  ('ikkeri', 'Ikkeri Nayaka', '1499 - 1763 CE', 'Various', 'Ikkeri', 'nayaka'),
  ('coorg', 'Kingdom of Coorg', '1600 - 1834 CE', 'Various', 'Madikeri', 'kodava'),
  ('jaffna', 'Kingdom of Jaffna', '1215 - 1624 CE', 'Various', 'Jaffna', 'jaffna'),
  ('kotte', 'Kingdom of Kotte', '1412 - 1597 CE', 'Various', 'Kotte', 'kotte'),
  ('kandy', 'Kingdom of Kandy', '1469 - 1815 CE', 'Various', 'Kandy', 'kandy'),
  ('polonnaruwa', 'Polonnaruwa Kingdom', '1056 - 1232 CE', 'Various', 'Polonnaruwa', 'polonnaruwa'),
  ('anuradhapura', 'Anuradhapura Kingdom', '377 BCE - 1017 CE', 'Various', 'Anuradhapura', 'anuradhapura'),
  ('ruhuna', 'Ruhuna Kingdom', '200 BCE - 1200 CE', 'Various', 'Magama', 'ruhuna'),
  ('sitawaka', 'Kingdom of Sitawaka', '1521 - 1594 CE', 'Mayadunne', 'Sitawaka', 'sitawaka'),
  ('licchavi', 'Licchavi Republic', '600 - 300 BCE', 'Various', 'Vaishali', 'mahajanapada'),
  ('kuru-panchala', 'Kuru-Panchala', '1200 - 500 BCE', 'Various', 'Hastinapura', 'vedic'),
  ('gana-sangha', 'Various Gana Sanghas', '600 - 300 BCE', 'Various', 'Various', 'gana'),
  ('kalachuri-ratnapura', 'Kalachuri of Ratnapura', '1000 - 1200 CE', 'Various', 'Ratnapura', 'kalachuri'),
  ('suryavamshi-gajapati', 'Suryavamshi Gajapati', '1434 - 1541 CE', 'Kapilendra Deva', 'Cuttack', 'gajapati'),
  ('madurai-nayak', 'Madurai Nayak', '1529 - 1736 CE', 'Various', 'Madurai', 'nayaka'),
  ('thanjavur-nayak', 'Thanjavur Nayak', '1532 - 1673 CE', 'Various', 'Thanjavur', 'nayaka'),
  ('gingee-nayak', 'Gingee Nayak', '1507 - 1648 CE', 'Various', 'Gingee', 'nayaka'),
  ('keladi-nayak', 'Keladi Nayak', '1499 - 1763 CE', 'Various', 'Ikkeri', 'nayaka'),
  ('kashmir-sultanate', 'Kashmir Sultanate', '1339 - 1586 CE', 'Shah Mir', 'Srinagar', 'kashmir'),
  ('bengal-nawab', 'Nawabs of Bengal', '1717 - 1880 CE', 'Murshid Quli Khan', 'Murshidabad', 'bengal'),
  ('hyderabad-nizam', 'Nizam of Hyderabad', '1724 - 1948 CE', 'Asaf Jah I', 'Hyderabad', 'nizam')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  period = EXCLUDED.period,
  founder = EXCLUDED.founder,
  capital = EXCLUDED.capital,
  civilization_id = EXCLUDED.civilization_id;