/*
# Enrich Personalities Batch D: Southern Dynasties (Rashtrakuta, Chalukya, Pallava, Chola, Kakatiya)

Records: p24-p43
*/

-- p24: Dantidurga
UPDATE personalities SET
  slug = 'dantidurga', title = 'Emperor', gender = 'Male',
  birth_year = NULL, death_year = 756, birth_text = NULL, death_text = '756 CE',
  categories = ARRAY['Ruler','Founder']::TEXT[],
  civilization = 'Rashtrakuta Empire', historical_period = 'Medieval India',
  dynasty = 'Rashtrakuta', kingdom = 'Deccan', religion = 'Hinduism',
  occupation = ARRAY['Emperor']::TEXT[],
  birthplace = NULL, death_place = 'Manyakheta',
  region = 'Deccan', present_state = 'Karnataka', present_country = 'India',
  short_description = 'Dantidurga was the founder of the Rashtrakuta Empire who overthrew the Chalukya king Kirtivarman II in 753 CE and established Rashtrakuta dominance over the Deccan region.',
  famous_for = 'Founding the Rashtrakuta Empire by defeating Chalukya Kirtivarman II in 753 CE. He laid the foundation for one of the most powerful Deccan dynasties.',
  achievements = ARRAY['Overthrew Chalukya Kirtivarman II in 753 CE','Established the Rashtrakuta Empire','Consolidated control over the Deccan region']::TEXT[],
  notable_works = ARRAY[]::TEXT[], notable_titles = ARRAY['Dantivarman']::TEXT[],
  active_start_year = 753, active_end_year = 756, century = '8th century CE', timeline_order = 15,
  father = NULL, mother = NULL, spouse = NULL, children = NULL,
  teacher = NULL, students = NULL,
  predecessor = 'Kirtivarman II', successor = 'Krishna I',
  contemporaries = ARRAY['Kirtivarman II']::TEXT[],
  related_people = ARRAY['Krishna I','Kirtivarman II']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Rashtrakuta','Chalukya of Badami']::TEXT[],
  related_kingdoms = ARRAY['Deccan']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Dantidurga',
  keywords = ARRAY['Dantidurga','Rashtrakuta','founder','Deccan','753 CE']::TEXT[],
  search_aliases = ARRAY['Dantivarman']::TEXT[],
  meta_description = 'Dantidurga founded the Rashtrakuta Empire in 753 CE by overthrowing Chalukya Kirtivarman II, establishing Deccan dominance.',
  verified = TRUE, featured = FALSE, updated_at = NOW()
WHERE id = 'p24';

-- p25: Krishna I
UPDATE personalities SET
  slug = 'krishna-i', title = 'Emperor', gender = 'Male',
  birth_year = NULL, death_year = 774, birth_text = NULL, death_text = '774 CE',
  categories = ARRAY['Ruler','Patron of Architecture']::TEXT[],
  civilization = 'Rashtrakuta Empire', historical_period = 'Medieval India',
  dynasty = 'Rashtrakuta', kingdom = 'Deccan', religion = 'Hinduism',
  occupation = ARRAY['Emperor']::TEXT[],
  birthplace = NULL, death_place = 'Manyakheta',
  region = 'Deccan', present_state = 'Karnataka', present_country = 'India',
  short_description = 'Krishna I was a Rashtrakuta emperor who reigned from 756 to 774 CE and is renowned for commissioning the Kailasa Temple at Ellora, a monolithic rock-cut structure and UNESCO World Heritage Site.',
  famous_for = 'Commissioning the Kailasa Temple (Cave 16) at Ellora, one of the greatest rock-cut architectural marvels in Indian history.',
  achievements = ARRAY['Commissioned the Kailasa Temple at Ellora (UNESCO World Heritage Site)','Expanded the Rashtrakuta Empire through military campaigns','Patron of Jain scholars including Akalanka']::TEXT[],
  notable_works = ARRAY['Kailasa Temple at Ellora']::TEXT[],
  notable_titles = ARRAY['Krishnaraja']::TEXT[],
  active_start_year = 756, active_end_year = 774, century = '8th century CE', timeline_order = 16,
  father = 'Dantidurga', mother = NULL, spouse = NULL,
  children = ARRAY['Govinda II','Dhruva Dharavarsha']::TEXT[],
  teacher = NULL, students = NULL,
  predecessor = 'Dantidurga', successor = 'Govinda II',
  contemporaries = ARRAY[]::TEXT[],
  related_people = ARRAY['Dantidurga','Dhruva Dharavarsha','Govinda II']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Rashtrakuta']::TEXT[],
  related_kingdoms = ARRAY[]::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Krishna_I',
  keywords = ARRAY['Krishna I','Rashtrakuta','Kailasa Temple','Ellora','rock-cut architecture','UNESCO']::TEXT[],
  search_aliases = ARRAY['Krishnaraja']::TEXT[],
  meta_description = 'Krishna I built the Kailasa Temple at Ellora, a UNESCO rock-cut marvel, and expanded the Rashtrakuta Empire from 756 to 774 CE.',
  verified = TRUE, featured = TRUE, updated_at = NOW()
WHERE id = 'p25';

-- p26: Dhruva Dharavarsha
UPDATE personalities SET
  slug = 'dhruva-dharavarsha', title = 'Emperor', gender = 'Male',
  birth_year = NULL, death_year = 793, birth_text = NULL, death_text = '793 CE',
  categories = ARRAY['Ruler','Military']::TEXT[],
  civilization = 'Rashtrakuta Empire', historical_period = 'Medieval India',
  dynasty = 'Rashtrakuta', kingdom = 'Deccan', religion = 'Hinduism',
  occupation = ARRAY['Emperor']::TEXT[],
  birthplace = NULL, death_place = 'Manyakheta',
  region = 'Deccan', present_state = 'Karnataka', present_country = 'India',
  short_description = 'Dhruva Dharavarsha reigned from 780 to 793 CE and transformed the Rashtrakuta kingdom into a major empire through military campaigns across northern and southern India, initiating the tripartite struggle for Kanauj.',
  famous_for = 'Expanding Rashtrakuta power by defeating the Gurjara-Pratihara ruler Vatsaraja and the Pala king Dharmapala, initiating the tripartite struggle for Kanauj.',
  achievements = ARRAY['Defeated Gurjara-Pratihara ruler Vatsaraja','Defeated Pala king Dharmapala','Reached the Ganges River in northern campaigns','Subdued the Western Ganga dynasty','Initiated the tripartite struggle for Kanauj']::TEXT[],
  notable_works = ARRAY[]::TEXT[], notable_titles = ARRAY['Dharavarsha']::TEXT[],
  active_start_year = 780, active_end_year = 793, century = '8th century CE', timeline_order = 17,
  father = 'Krishna I', mother = NULL, spouse = NULL,
  children = ARRAY['Govinda III']::TEXT[],
  teacher = NULL, students = NULL,
  predecessor = 'Govinda II', successor = 'Govinda III',
  contemporaries = ARRAY['Vatsaraja','Dharmapala']::TEXT[],
  related_people = ARRAY['Krishna I','Govinda II','Govinda III','Vatsaraja','Dharmapala']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Rashtrakuta','Gurjara-Pratihara','Pala']::TEXT[],
  related_kingdoms = ARRAY['Deccan']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Dhruva_Dharavarsha',
  keywords = ARRAY['Dhruva','Dharavarsha','Rashtrakuta','tripartite struggle','Vatsaraja','Dharmapala','Kanauj']::TEXT[],
  search_aliases = ARRAY['Dhruva I']::TEXT[],
  meta_description = 'Dhruva Dharavarsha expanded the Rashtrakuta Empire (780-793 CE), defeating Vatsaraja and Dharmapala, starting the tripartite struggle.',
  verified = TRUE, featured = FALSE, updated_at = NOW()
WHERE id = 'p26';

-- p27: Govinda III
UPDATE personalities SET
  slug = 'govinda-iii', title = 'Emperor', gender = 'Male',
  birth_year = NULL, death_year = 814, birth_text = NULL, death_text = '814 CE',
  categories = ARRAY['Ruler','Military']::TEXT[],
  civilization = 'Rashtrakuta Empire', historical_period = 'Medieval India',
  dynasty = 'Rashtrakuta', kingdom = 'Deccan', religion = 'Hinduism',
  occupation = ARRAY['Emperor']::TEXT[],
  birthplace = NULL, death_place = 'Manyakheta',
  region = 'Deccan', present_state = 'Karnataka', present_country = 'India',
  short_description = 'Govinda III reigned from 793 to 814 CE and was militarily the most successful emperor of the Rashtrakuta dynasty, with conquests stretching from Kanyakumari in the south to Kanyakubja in the north.',
  famous_for = 'Being the most militarily successful Rashtrakuta emperor, with conquests spanning from Kanyakumari to Kanyakubja and from Banaras to the Arabian Sea.',
  achievements = ARRAY['Conquered territories from Kanyakumari to Kanyakubja','Defeated Gurjara-Pratihara ruler Nagabhata II','Defeated the Pala king Dharmapala','Subdued the Western Gangas']::TEXT[],
  notable_works = ARRAY[]::TEXT[], notable_titles = ARRAY['Jagattunga']::TEXT[],
  active_start_year = 793, active_end_year = 814, century = '9th century CE', timeline_order = 18,
  father = 'Dhruva Dharavarsha', mother = NULL, spouse = NULL,
  children = ARRAY['Amoghavarsha I']::TEXT[],
  teacher = NULL, students = NULL,
  predecessor = 'Dhruva Dharavarsha', successor = 'Amoghavarsha I',
  contemporaries = ARRAY['Nagabhata II','Dharmapala']::TEXT[],
  related_people = ARRAY['Dhruva Dharavarsha','Amoghavarsha I','Nagabhata II','Dharmapala']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Rashtrakuta','Gurjara-Pratihara','Pala']::TEXT[],
  related_kingdoms = ARRAY['Deccan']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Govinda_III',
  keywords = ARRAY['Govinda III','Rashtrakuta','conqueror','Kanyakumari','Kanyakubja','Jagattunga']::TEXT[],
  search_aliases = ARRAY[]::TEXT[],
  meta_description = 'Govinda III (793-814 CE) was the most militarily successful Rashtrakuta emperor, conquering from Kanyakumari to Kanyakubja.',
  verified = TRUE, featured = FALSE, updated_at = NOW()
WHERE id = 'p27';

-- p28: Amoghavarsha I
UPDATE personalities SET
  slug = 'amoghavarsha-i', title = 'Emperor', gender = 'Male',
  birth_year = 800, death_year = 878, birth_text = '800 CE', death_text = '878 CE',
  categories = ARRAY['Ruler','Scholar','Patron of Arts']::TEXT[],
  civilization = 'Rashtrakuta Empire', historical_period = 'Medieval India',
  dynasty = 'Rashtrakuta', kingdom = 'Deccan', religion = 'Jainism',
  occupation = ARRAY['Emperor','Scholar']::TEXT[],
  birthplace = NULL, death_place = 'Manyakheta',
  region = 'Deccan', present_state = 'Karnataka', present_country = 'India',
  short_description = 'Amoghavarsha I (r. 814-878 CE) is widely considered the greatest Rashtrakuta emperor. His reign of 64 years is one of the longest precisely dated monarchical reigns in history. He wrote the Kavirajamarga, the earliest available Kannada literary work.',
  famous_for = 'Writing the Kavirajamarga, the earliest extant literary work in Kannada. The Arab traveler Sulaiman described him as one of the four great kings of the world.',
  achievements = ARRAY['Authored Kavirajamarga, earliest Kannada literary work','Ruled for 64 years, one of the longest reigns on record','Patron of Jain mathematician Mahaviracharya','Moved capital to Manyakheta','Compared to Emperor Ashoka as Ashoka of the South']::TEXT[],
  notable_works = ARRAY['Kavirajamarga']::TEXT[],
  notable_titles = ARRAY['Nrupatunga','Vira-Narayana']::TEXT[],
  active_start_year = 814, active_end_year = 878, century = '9th century CE', timeline_order = 19,
  father = 'Govinda III', mother = NULL, spouse = NULL,
  children = ARRAY['Krishna II']::TEXT[],
  teacher = NULL, students = NULL,
  predecessor = 'Govinda III', successor = 'Krishna II',
  contemporaries = ARRAY['Mahaviracharya','Jinasena','Sulaiman']::TEXT[],
  related_people = ARRAY['Govinda III','Mahaviracharya','Jinasena']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Rashtrakuta']::TEXT[],
  related_kingdoms = ARRAY[]::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Amoghavarsha',
  keywords = ARRAY['Amoghavarsha','Rashtrakuta','Kavirajamarga','Kannada','Nrupatunga','Ashoka of the South','Jainism']::TEXT[],
  search_aliases = ARRAY['Nrupatunga']::TEXT[],
  meta_description = 'Amoghavarsha I (814-878 CE), greatest Rashtrakuta emperor, wrote Kavirajamarga and ruled 64 years. Called Ashoka of the South.',
  verified = TRUE, featured = TRUE, updated_at = NOW()
WHERE id = 'p28';

-- p29: Pulakeshin II
UPDATE personalities SET
  slug = 'pulakeshin-ii', title = 'Emperor', gender = 'Male',
  birth_year = NULL, death_year = 642, birth_text = NULL, death_text = 'c. 642 CE',
  categories = ARRAY['Ruler','Military']::TEXT[],
  civilization = 'Chalukya Dynasty', historical_period = 'Classical India',
  dynasty = 'Chalukya of Badami', kingdom = 'Deccan', religion = 'Hinduism',
  occupation = ARRAY['Emperor']::TEXT[],
  birthplace = NULL, death_place = 'Vatapi (Badami)',
  region = 'Deccan', present_state = 'Karnataka', present_country = 'India',
  short_description = 'Pulakeshin II (r. c. 610-642 CE) was the most famous ruler of the Chalukya dynasty of Vatapi who expanded the Chalukya kingdom to cover most of the Deccan and famously defeated Harshavardhana of Kanauj.',
  famous_for = 'Defeating Harshavardhana of Kanauj on the banks of the Narmada River, preventing the northern emperor from expanding southward. His Aihole inscription is a masterpiece of Sanskrit poetry by Ravikirti.',
  achievements = ARRAY['Defeated Harshavardhana of Kanauj c. 618 CE','Expanded Chalukya kingdom across most of the Deccan','Defeated Kadambas of Banavasi','Received Persian embassy from Khosrow II','Aihole inscription by Ravikirti documents his conquests']::TEXT[],
  notable_works = ARRAY[]::TEXT[], notable_titles = ARRAY['Satyashraya','Prithvivallabha']::TEXT[],
  active_start_year = 610, active_end_year = 642, century = '7th century CE', timeline_order = 15,
  father = 'Kirtivarman I', mother = NULL, spouse = NULL,
  children = ARRAY['Vikramaditya I','Jayasimha']::TEXT[],
  teacher = NULL, students = NULL,
  predecessor = 'Mangalesha', successor = 'Vikramaditya I',
  contemporaries = ARRAY['Harshavardhana','Xuanzang','Khosrow II']::TEXT[],
  related_people = ARRAY['Mangalesha','Harshavardhana','Vikramaditya I','Ravikirti','Xuanzang']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Chalukya of Badami','Vardhana','Pallava']::TEXT[],
  related_kingdoms = ARRAY['Deccan']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Pulakeshin_II',
  keywords = ARRAY['Pulakeshin II','Chalukya','Vatapi','Badami','Harsha','Narmada','Aihole inscription','Ravikirti']::TEXT[],
  search_aliases = ARRAY['Immadi Pulakeshi','Pulakesi II']::TEXT[],
  meta_description = 'Pulakeshin II (610-642 CE) defeated Harsha at Narmada, expanding the Chalukya Empire across the Deccan from Vatapi.',
  verified = TRUE, featured = TRUE, updated_at = NOW()
WHERE id = 'p29';

-- p30: Vikramaditya II
UPDATE personalities SET
  slug = 'vikramaditya-ii', title = 'Emperor', gender = 'Male',
  birth_year = NULL, death_year = 744, birth_text = NULL, death_text = 'c. 744 CE',
  categories = ARRAY['Ruler','Military']::TEXT[],
  civilization = 'Chalukya Dynasty', historical_period = 'Classical India',
  dynasty = 'Chalukya of Badami', kingdom = 'Deccan', religion = 'Hinduism',
  occupation = ARRAY['Emperor']::TEXT[],
  birthplace = NULL, death_place = 'Badami',
  region = 'Deccan', present_state = 'Karnataka', present_country = 'India',
  short_description = 'Vikramaditya II (r. 733-744 CE) was a Badami Chalukya emperor who achieved decisive victories over the Pallavas, sacking their capital Kanchipuram three times and patronizing the Virupaksha Temple at Pattadakal.',
  famous_for = 'Defeating the Pallavas and capturing their capital Kanchipuram multiple times, avenging earlier Chalukya defeats.',
  achievements = ARRAY['Defeated Pallava king Nandivarman II and captured Kanchipuram','Sacked Pallava capital three times','Left victory inscriptions at Kanchi Kailasanatha Temple','Patronized the Virupaksha Temple at Pattadakal (UNESCO site)']::TEXT[],
  notable_works = ARRAY[]::TEXT[], notable_titles = ARRAY['Satyashraya','Rajamalla']::TEXT[],
  active_start_year = 733, active_end_year = 744, century = '8th century CE', timeline_order = 16,
  father = 'Vijayaditya', mother = NULL,
  spouse = ARRAY['Lokamahadevi','Trailokyamahadevi']::TEXT[],
  children = ARRAY['Kirtivarman II']::TEXT[],
  teacher = NULL, students = NULL,
  predecessor = 'Vijayaditya', successor = 'Kirtivarman II',
  contemporaries = ARRAY['Nandivarman II']::TEXT[],
  related_people = ARRAY['Vijayaditya','Nandivarman II','Kirtivarman II']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Chalukya of Badami','Pallava']::TEXT[],
  related_kingdoms = ARRAY['Deccan']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Vikramaditya_II',
  keywords = ARRAY['Vikramaditya II','Chalukya','Badami','Pallava','Kanchipuram','Pattadakal','Virupaksha Temple']::TEXT[],
  search_aliases = ARRAY[]::TEXT[],
  meta_description = 'Vikramaditya II (733-744 CE) defeated the Pallavas, sacking Kanchipuram and building the Virupaksha Temple at Pattadakal.',
  verified = TRUE, featured = FALSE, updated_at = NOW()
WHERE id = 'p30';

-- p31: Narasimhavarman I
UPDATE personalities SET
  slug = 'narasimhavarman-i', title = 'Emperor', gender = 'Male',
  birth_year = NULL, death_year = 668, birth_text = NULL, death_text = '668 CE',
  categories = ARRAY['Ruler','Military','Patron of Arts']::TEXT[],
  civilization = 'Pallava Dynasty', historical_period = 'Classical India',
  dynasty = 'Pallava', kingdom = 'Tondaimandalam', religion = 'Hinduism',
  occupation = ARRAY['Emperor']::TEXT[],
  birthplace = NULL, death_place = 'Kanchipuram',
  region = 'Tamilakam', present_state = 'Tamil Nadu', present_country = 'India',
  short_description = 'Narasimhavarman I (r. 630-668 CE) was a powerful Pallava emperor who avenged his father''s defeat by destroying the Chalukya capital Vatapi and killing Pulakeshin II in 642 CE. Mamallapuram was named in his honor.',
  famous_for = 'Defeating and killing Pulakeshin II of the Chalukyas in 642 CE, sacking the Chalukya capital Vatapi. The Pancha Rathas at Mamallapuram were constructed during his reign.',
  achievements = ARRAY['Defeated and killed Pulakeshin II in 642 CE','Captured and destroyed the Chalukya capital Vatapi','Completed the Pancha Rathas at Mamallapuram (UNESCO site)','Patronized the Nayanar saints Appar and Sambandar','Sent naval expeditions to Sri Lanka']::TEXT[],
  notable_works = ARRAY[]::TEXT[], notable_titles = ARRAY['Mamallan','Mahamalla']::TEXT[],
  active_start_year = 630, active_end_year = 668, century = '7th century CE', timeline_order = 15,
  father = 'Mahendravarman I', mother = NULL, spouse = NULL,
  children = ARRAY['Mahendravarman II']::TEXT[],
  teacher = NULL, students = NULL,
  predecessor = 'Mahendravarman I', successor = 'Mahendravarman II',
  contemporaries = ARRAY['Pulakeshin II','Appar','Sambandar']::TEXT[],
  related_people = ARRAY['Mahendravarman I','Pulakeshin II','Mahendravarman II','Appar','Sambandar']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Pallava','Chalukya of Badami']::TEXT[],
  related_kingdoms = ARRAY['Tondaimandalam']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Narasimhavarman_I',
  keywords = ARRAY['Narasimhavarman I','Pallava','Mamallan','Mamallapuram','Pulakeshin II','Vatapi','Pancha Rathas']::TEXT[],
  search_aliases = ARRAY['Mamallan','Mahamalla']::TEXT[],
  meta_description = 'Narasimhavarman I (630-668 CE) defeated and killed Pulakeshin II, sacking Vatapi. Mamallapuram was named after him.',
  verified = TRUE, featured = TRUE, updated_at = NOW()
WHERE id = 'p31';

-- p32: Mahendravarman I
UPDATE personalities SET
  slug = 'mahendravarman-i', title = 'Emperor', gender = 'Male',
  birth_year = NULL, death_year = 630, birth_text = NULL, death_text = '630 CE',
  categories = ARRAY['Ruler','Playwright','Patron of Arts']::TEXT[],
  civilization = 'Pallava Dynasty', historical_period = 'Classical India',
  dynasty = 'Pallava', kingdom = 'Tondaimandalam', religion = 'Hinduism',
  occupation = ARRAY['Emperor','Playwright']::TEXT[],
  birthplace = NULL, death_place = 'Kanchipuram',
  region = 'Tamilakam', present_state = 'Tamil Nadu', present_country = 'India',
  short_description = 'Mahendravarman I (r. c. 600-630 CE) was a Pallava emperor renowned as a scholar, playwright, and pioneer of rock-cut architecture who authored the Sanskrit farce Mattavilasa Prahasana and initiated the earliest rock-cut cave temples of the Pallavas.',
  famous_for = 'Writing the Sanskrit satire Mattavilasa Prahasana and pioneering rock-cut architecture among the Pallavas. He was defeated by Pulakeshin II of the Chalukyas.',
  achievements = ARRAY['Authored Mattavilasa Prahasana (Sanskrit farce)','Authored Bhagavadajjuka (Sanskrit play)','Pioneered rock-cut cave architecture among the Pallavas','Built cave temples at Pallavaram, Mahendravadi, and Mandagapattu']::TEXT[],
  notable_works = ARRAY['Mattavilasa Prahasana','Bhagavadajjuka']::TEXT[],
  notable_titles = ARRAY['Mattavilasa','Vichitrachitta']::TEXT[],
  active_start_year = 600, active_end_year = 630, century = '7th century CE', timeline_order = 15,
  father = 'Simhavishnu', mother = NULL, spouse = NULL,
  children = ARRAY['Narasimhavarman I']::TEXT[],
  teacher = NULL, students = NULL,
  predecessor = 'Simhavishnu', successor = 'Narasimhavarman I',
  contemporaries = ARRAY['Pulakeshin II','Appar']::TEXT[],
  related_people = ARRAY['Simhavishnu','Narasimhavarman I','Pulakeshin II','Appar']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Pallava','Chalukya of Badami']::TEXT[],
  related_kingdoms = ARRAY['Tondaimandalam']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Mahendravarman_I',
  keywords = ARRAY['Mahendravarman I','Pallava','Mattavilasa Prahasana','rock-cut architecture','Sanskrit play','Vichitrachitta']::TEXT[],
  search_aliases = ARRAY['Mattavilasa']::TEXT[],
  meta_description = 'Mahendravarman I (600-630 CE) was a Pallava king, playwright, and pioneer of rock-cut architecture who wrote Mattavilasa Prahasana.',
  verified = TRUE, featured = FALSE, updated_at = NOW()
WHERE id = 'p32';

-- p33: Rajendra I Chola
UPDATE personalities SET
  slug = 'rajendra-i-chola', title = 'Emperor', gender = 'Male',
  birth_year = 971, death_year = 1044, birth_text = '971 CE', death_text = '1044 CE',
  categories = ARRAY['Ruler','Military','Naval Commander']::TEXT[],
  civilization = 'Chola Empire', historical_period = 'Medieval India',
  dynasty = 'Chola Dynasty', kingdom = 'Chola Nadu', religion = 'Hinduism',
  occupation = ARRAY['Emperor']::TEXT[],
  birthplace = 'Thanjavur', death_place = 'Gangaikondacholapuram',
  region = 'Tamilakam', present_state = 'Tamil Nadu', present_country = 'India',
  short_description = 'Rajendra I (r. 1014-1044 CE) was one of the greatest Chola emperors who expanded the empire to its greatest extent, conquering territories up to the Ganges and launching a historic naval expedition against the Srivijaya Empire in Southeast Asia.',
  famous_for = 'Leading the unprecedented naval expedition against the Srivijaya Empire in 1025 CE, conquering parts of Indonesia and Malaysia. He also marched to the Ganges, earning the title Gangaikonda Chola.',
  achievements = ARRAY['Conquered territories from Tamil Nadu to the Ganges River','Launched naval expedition against Srivijaya Empire in 1025 CE','Conquered Sri Lanka and the Maldives','Annexed Kalinga and Bengal','Built Gangaikondacholapuram and Brihadisvara Temple there']::TEXT[],
  notable_works = ARRAY['Brihadisvara Temple at Gangaikondacholapuram']::TEXT[],
  notable_titles = ARRAY['Gangaikonda Chola','Mummadi Chola','Rajadhiraja']::TEXT[],
  active_start_year = 1012, active_end_year = 1044, century = '11th century CE', timeline_order = 20,
  father = 'Rajaraja I', mother = 'Vanavan Mahadevi',
  spouse = ARRAY[]::TEXT[],
  children = ARRAY['Rajadhiraja I','Rajendra II','Virarajendra']::TEXT[],
  teacher = NULL, students = NULL,
  predecessor = 'Rajaraja I', successor = 'Rajadhiraja I',
  contemporaries = ARRAY[]::TEXT[],
  related_people = ARRAY['Rajaraja I','Rajadhiraja I','Rajendra II','Virarajendra']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Chola','Srivijaya','Western Chalukya']::TEXT[],
  related_kingdoms = ARRAY['Chola Nadu']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Rajendra_I',
  keywords = ARRAY['Rajendra I','Chola','Gangaikonda Chola','Srivijaya','naval expedition','Ganges','Gangaikondacholapuram','Southeast Asia']::TEXT[],
  search_aliases = ARRAY['Gangaikonda Chola','Rajendra Chola I']::TEXT[],
  meta_description = 'Rajendra I (1014-1044 CE) expanded the Chola Empire to the Ganges and launched a historic naval expedition against Srivijaya in 1025.',
  verified = TRUE, featured = TRUE, updated_at = NOW()
WHERE id = 'p33';

-- p34: Rajaraja II Chola
UPDATE personalities SET
  slug = 'rajaraja-ii-chola', title = 'Emperor', gender = 'Male',
  birth_year = NULL, death_year = 1173, birth_text = NULL, death_text = 'c. 1173 CE',
  categories = ARRAY['Ruler','Patron of Architecture']::TEXT[],
  civilization = 'Chola Empire', historical_period = 'Medieval India',
  dynasty = 'Chola Dynasty', kingdom = 'Chola Nadu', religion = 'Hinduism',
  occupation = ARRAY['Emperor']::TEXT[],
  birthplace = NULL, death_place = NULL,
  region = 'Tamilakam', present_state = 'Tamil Nadu', present_country = 'India',
  short_description = 'Rajaraja II (r. c. 1146-1173 CE) was a later Chola emperor who commissioned the magnificent Airavatesvara Temple at Darasuram, a UNESCO World Heritage Site. His reign saw the beginning of the empire''s decline.',
  famous_for = 'Building the Airavatesvara Temple at Darasuram, one of the three Great Living Chola Temples designated as UNESCO World Heritage Sites.',
  achievements = ARRAY['Commissioned the Airavatesvara Temple at Darasuram (UNESCO World Heritage Site)','Maintained control over core Chola territories','Preserved Chola cultural and architectural traditions']::TEXT[],
  notable_works = ARRAY['Airavatesvara Temple at Darasuram']::TEXT[],
  notable_titles = ARRAY['Rajakesari']::TEXT[],
  active_start_year = 1146, active_end_year = 1173, century = '12th century CE', timeline_order = 22,
  father = 'Kulothunga II', mother = NULL, spouse = NULL,
  children = ARRAY['Rajadhiraja II']::TEXT[],
  teacher = NULL, students = NULL,
  predecessor = 'Kulothunga II', successor = 'Rajadhiraja II',
  contemporaries = ARRAY[]::TEXT[],
  related_people = ARRAY['Kulothunga II','Rajadhiraja II']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Chola']::TEXT[],
  related_kingdoms = ARRAY['Chola Nadu']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Rajaraja_II',
  keywords = ARRAY['Rajaraja II','Chola','Airavatesvara Temple','Darasuram','UNESCO','Great Living Chola Temples']::TEXT[],
  search_aliases = ARRAY['Rajaraja Chola II']::TEXT[],
  meta_description = 'Rajaraja II (1146-1173 CE) built the Airavatesvara Temple at Darasuram, a UNESCO site, as the Chola Empire began its decline.',
  verified = TRUE, featured = FALSE, updated_at = NOW()
WHERE id = 'p34';

-- p35: Kulothunga I Chola
UPDATE personalities SET
  slug = 'kulothunga-i-chola', title = 'Emperor', gender = 'Male',
  birth_year = NULL, death_year = 1122, birth_text = NULL, death_text = 'c. 1122 CE',
  categories = ARRAY['Ruler','Patron of Arts']::TEXT[],
  civilization = 'Chola Empire', historical_period = 'Medieval India',
  dynasty = 'Chola Dynasty', kingdom = 'Chola Nadu', religion = 'Hinduism',
  occupation = ARRAY['Emperor']::TEXT[],
  birthplace = 'Vengi', death_place = 'Gangaikondacholapuram',
  region = 'Tamilakam', present_state = 'Tamil Nadu', present_country = 'India',
  short_description = 'Kulothunga I (r. 1070-1122 CE) united the Chola and Eastern Chalukya dynasties through inheritance from both parental lines, creating the Chalukya-Chola dynasty and ruling for 52 years.',
  famous_for = 'Uniting the Chola and Eastern Chalukya kingdoms into a single empire, establishing the Chalukya-Chola dynasty. The Tamil poem Kalingattuparani was composed during his reign.',
  achievements = ARRAY['United the Chola and Eastern Chalukya dynasties','Ruled as both Chola emperor and Eastern Chalukya king','Commissioned the Tamil epic Kalingattuparani by Jayamkondan','Conducted successful Kalinga campaign','Sent diplomatic missions to China']::TEXT[],
  notable_works = ARRAY[]::TEXT[], notable_titles = ARRAY['Tribhuvana Chakravartin']::TEXT[],
  active_start_year = 1070, active_end_year = 1122, century = '11th century CE', timeline_order = 21,
  father = 'Rajaraja Narendra', mother = 'Ammaiyadevi', spouse = NULL,
  children = ARRAY['Vikrama Chola']::TEXT[],
  teacher = NULL, students = NULL,
  predecessor = 'Athirajendra', successor = 'Vikrama Chola',
  contemporaries = ARRAY['Jayamkondan','Vikramaditya VI']::TEXT[],
  related_people = ARRAY['Rajaraja Narendra','Rajendra Chola I','Vikrama Chola','Jayamkondan']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Chola','Eastern Chalukya','Western Chalukya']::TEXT[],
  related_kingdoms = ARRAY['Chola Nadu']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Kulottunga_I',
  keywords = ARRAY['Kulothunga I','Chola','Chalukya-Chola','Eastern Chalukya','Kalingattuparani','Jayamkondan']::TEXT[],
  search_aliases = ARRAY['Kulottunga I','Rajendra Chalukya']::TEXT[],
  meta_description = 'Kulothunga I (1070-1122 CE) united the Chola and Eastern Chalukya dynasties, creating the Chalukya-Chola Empire.',
  verified = TRUE, featured = FALSE, updated_at = NOW()
WHERE id = 'p35';

-- p36: Aditya I Chola
UPDATE personalities SET
  slug = 'aditya-i-chola', title = 'King', gender = 'Male',
  birth_year = NULL, death_year = 907, birth_text = NULL, death_text = '907 CE',
  categories = ARRAY['Ruler','Founder']::TEXT[],
  civilization = 'Chola Empire', historical_period = 'Medieval India',
  dynasty = 'Chola Dynasty', kingdom = 'Chola Nadu', religion = 'Hinduism',
  occupation = ARRAY['King']::TEXT[],
  birthplace = NULL, death_place = NULL,
  region = 'Tamilakam', present_state = 'Tamil Nadu', present_country = 'India',
  short_description = 'Aditya I (r. c. 871-907 CE) was the son of Vijayalaya who expanded the Chola kingdom significantly by defeating the Pallava king Aparajita and annexing the Tondaimandalam region, laying the foundation for imperial Chola power.',
  famous_for = 'Defeating the Pallava king Aparajita and ending Pallava rule in Tondaimandalam, establishing the Cholas as the dominant power in the Tamil region.',
  achievements = ARRAY['Defeated Pallava king Aparajita and annexed Tondaimandalam','Ended Pallava supremacy in the Tamil region','Expanded Chola territory from the Kaveri delta to the Pallava country','Built numerous Shiva temples across his territories']::TEXT[],
  notable_works = ARRAY[]::TEXT[], notable_titles = ARRAY['Rajakesari','Kodandarama']::TEXT[],
  active_start_year = 871, active_end_year = 907, century = '9th century CE', timeline_order = 18,
  father = 'Vijayalaya', mother = NULL, spouse = NULL,
  children = ARRAY['Parantaka I']::TEXT[],
  teacher = NULL, students = NULL,
  predecessor = 'Vijayalaya', successor = 'Parantaka I',
  contemporaries = ARRAY['Aparajita']::TEXT[],
  related_people = ARRAY['Vijayalaya','Parantaka I','Aparajita']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Chola','Pallava']::TEXT[],
  related_kingdoms = ARRAY['Chola Nadu']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Aditya_I',
  keywords = ARRAY['Aditya I','Chola','Pallava','Aparajita','Tondaimandalam','Rajakesari']::TEXT[],
  search_aliases = ARRAY['Aditya Chola I']::TEXT[],
  meta_description = 'Aditya I (871-907 CE) defeated the Pallavas and expanded the Chola kingdom, establishing the foundation of imperial Chola power.',
  verified = TRUE, featured = FALSE, updated_at = NOW()
WHERE id = 'p36';

-- p37: Vijayalaya Chola
UPDATE personalities SET
  slug = 'vijayalaya-chola', title = 'King', gender = 'Male',
  birth_year = NULL, death_year = 871, birth_text = NULL, death_text = 'c. 871 CE',
  categories = ARRAY['Ruler','Founder']::TEXT[],
  civilization = 'Chola Empire', historical_period = 'Medieval India',
  dynasty = 'Chola Dynasty', kingdom = 'Chola Nadu', religion = 'Hinduism',
  occupation = ARRAY['King']::TEXT[],
  birthplace = NULL, death_place = 'Thanjavur',
  region = 'Tamilakam', present_state = 'Tamil Nadu', present_country = 'India',
  short_description = 'Vijayalaya (r. c. 848-871 CE) was the founder of the imperial Chola Empire who captured Thanjavur in 850 CE and established the Chola dynasty that would become one of the most powerful maritime empires in Indian history.',
  famous_for = 'Capturing Thanjavur in 850 CE and founding the imperial Chola dynasty, reviving Chola power after centuries of obscurity.',
  achievements = ARRAY['Captured Thanjavur in 850 CE','Founded the imperial Chola Empire','Established Thanjavur as the Chola capital','Revived the Chola dynasty after centuries of obscurity']::TEXT[],
  notable_works = ARRAY[]::TEXT[], notable_titles = ARRAY[]::TEXT[],
  active_start_year = 848, active_end_year = 871, century = '9th century CE', timeline_order = 17,
  father = NULL, mother = NULL, spouse = NULL,
  children = ARRAY['Aditya I']::TEXT[],
  teacher = NULL, students = NULL,
  predecessor = NULL, successor = 'Aditya I',
  contemporaries = ARRAY[]::TEXT[],
  related_people = ARRAY['Aditya I','Parantaka I']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Chola','Pallava']::TEXT[],
  related_kingdoms = ARRAY['Chola Nadu']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Vijayalaya',
  keywords = ARRAY['Vijayalaya','Chola','founder','Thanjavur','850 CE','imperial Chola']::TEXT[],
  search_aliases = ARRAY[]::TEXT[],
  meta_description = 'Vijayalaya founded the imperial Chola Empire by capturing Thanjavur in 850 CE, reviving the dynasty after centuries of obscurity.',
  verified = TRUE, featured = FALSE, updated_at = NOW()
WHERE id = 'p37';

-- p38: Parantaka I Chola
UPDATE personalities SET
  slug = 'parantaka-i-chola', title = 'Emperor', gender = 'Male',
  birth_year = NULL, death_year = 955, birth_text = NULL, death_text = '955 CE',
  categories = ARRAY['Ruler','Military']::TEXT[],
  civilization = 'Chola Empire', historical_period = 'Medieval India',
  dynasty = 'Chola Dynasty', kingdom = 'Chola Nadu', religion = 'Hinduism',
  occupation = ARRAY['Emperor']::TEXT[],
  birthplace = NULL, death_place = NULL,
  region = 'Tamilakam', present_state = 'Tamil Nadu', present_country = 'India',
  short_description = 'Parantaka I (r. 907-955 CE) was a Chola emperor who reigned for 48 years and transformed the Chola kingdom into a major empire by annexing the Pandya kingdom and extending Chola influence across the Tamil country.',
  famous_for = 'Conquering the Pandya kingdom and earning the title Maduraikondavan (conqueror of Madurai). He also defeated the Rashtrakutas and extended Chola territory to the southern tip of India.',
  achievements = ARRAY['Annexed the Pandya kingdom by defeating Rajasimha II','Earned the title Maduraikondavan','Defeated the Rashtrakuta king Krishna II','Extended Chola territory across the Tamil country','Ruled for 48 years']::TEXT[],
  notable_works = ARRAY[]::TEXT[], notable_titles = ARRAY['Maduraikondavan','Veera Chola']::TEXT[],
  active_start_year = 907, active_end_year = 955, century = '10th century CE', timeline_order = 19,
  father = 'Aditya I', mother = NULL, spouse = NULL,
  children = ARRAY['Gandaraditya','Arinjaya']::TEXT[],
  teacher = NULL, students = NULL,
  predecessor = 'Aditya I', successor = 'Gandaraditya',
  contemporaries = ARRAY['Krishna II','Rajasimha II']::TEXT[],
  related_people = ARRAY['Aditya I','Gandaraditya','Arinjaya','Krishna II','Rajasimha II']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Chola','Pandya','Rashtrakuta']::TEXT[],
  related_kingdoms = ARRAY['Chola Nadu']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Parantaka_I',
  keywords = ARRAY['Parantaka I','Chola','Maduraikondavan','Pandya','Madurai','Rajasimha II']::TEXT[],
  search_aliases = ARRAY['Parantaka Chola I']::TEXT[],
  meta_description = 'Parantaka I (907-955 CE) expanded the Chola Empire, conquering Madurai and earning the title Maduraikondavan over 48 years.',
  verified = TRUE, featured = FALSE, updated_at = NOW()
WHERE id = 'p38';

-- p39: Raja Raja Narendra
UPDATE personalities SET
  slug = 'raja-raja-narendra', title = 'King', gender = 'Male',
  birth_year = NULL, death_year = 1061, birth_text = NULL, death_text = '1061 CE',
  categories = ARRAY['Ruler','Patron of Literature']::TEXT[],
  civilization = 'Eastern Chalukya Dynasty', historical_period = 'Medieval India',
  dynasty = 'Eastern Chalukya', kingdom = 'Vengi', religion = 'Hinduism',
  occupation = ARRAY['King']::TEXT[],
  birthplace = 'Vengi', death_place = 'Rajahmundry',
  region = 'Andhra', present_state = 'Andhra Pradesh', present_country = 'India',
  short_description = 'Rajaraja Narendra (r. 1019-1061 CE) was the Eastern Chalukya king of the Vengi kingdom who commissioned the Andhra Mahabharatam, the first Telugu rendering of the Mahabharata by poet Nannaya, founding Telugu literature.',
  famous_for = 'Commissioning the Andhra Mahabharatam, the foundational work of Telugu literature, rendered by the poet Nannaya Bhatta. He was the father of Kulothunga I.',
  achievements = ARRAY['Commissioned the Andhra Mahabharatam by Nannaya Bhatta','Fostered the development of Telugu as a literary language','Maintained the Vengi kingdom amid Chola-Western Chalukya conflicts','Father of Kulothunga I, future Chola emperor']::TEXT[],
  notable_works = ARRAY[]::TEXT[], notable_titles = ARRAY[]::TEXT[],
  active_start_year = 1019, active_end_year = 1061, century = '11th century CE', timeline_order = 20,
  father = 'Vimaladitya', mother = NULL,
  spouse = ARRAY['Ammaiyadevi']::TEXT[],
  children = ARRAY['Kulothunga I']::TEXT[],
  teacher = NULL, students = NULL,
  predecessor = 'Vimaladitya', successor = 'Saktivarman II',
  contemporaries = ARRAY['Rajendra Chola I','Nannaya Bhatta']::TEXT[],
  related_people = ARRAY['Vimaladitya','Kulothunga I','Rajendra Chola I','Nannaya Bhatta']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Eastern Chalukya','Chola']::TEXT[],
  related_kingdoms = ARRAY['Vengi']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Rajaraja_Narendra',
  keywords = ARRAY['Rajaraja Narendra','Eastern Chalukya','Vengi','Telugu literature','Andhra Mahabharatam','Nannaya','Kulothunga I']::TEXT[],
  search_aliases = ARRAY['Raja Raja Narendra']::TEXT[],
  meta_description = 'Rajaraja Narendra (1019-1061 CE) commissioned the Andhra Mahabharatam by Nannaya, founding Telugu literature in the Vengi kingdom.',
  verified = TRUE, featured = FALSE, updated_at = NOW()
WHERE id = 'p39';

-- p40: Somesvara I Chalukya
UPDATE personalities SET
  slug = 'somesvara-i-chalukya', title = 'Emperor', gender = 'Male',
  birth_year = NULL, death_year = 1068, birth_text = NULL, death_text = '1068 CE',
  categories = ARRAY['Ruler','Military']::TEXT[],
  civilization = 'Western Chalukya Dynasty', historical_period = 'Medieval India',
  dynasty = 'Western Chalukya', kingdom = 'Deccan', religion = 'Hinduism',
  occupation = ARRAY['Emperor']::TEXT[],
  birthplace = NULL, death_place = 'Kalyani',
  region = 'Deccan', present_state = 'Karnataka', present_country = 'India',
  short_description = 'Somesvara I (r. 1042-1068 CE), also known as Ahavamalla, was a Western Chalukya emperor who shifted the capital to Kalyani and fought several wars against the Cholas over control of Vengi.',
  famous_for = 'Shifting the Western Chalukya capital to Kalyani and engaging in protracted warfare with the Chola Empire over the strategically important Vengi region.',
  achievements = ARRAY['Shifted the Western Chalukya capital to Kalyani','Fought major campaigns against Chola kings Rajadhiraja I and Rajendra II','Defeated and killed Chola king Rajadhiraja I at the Battle of Koppam in 1052','Maintained Western Chalukya supremacy over the Deccan']::TEXT[],
  notable_works = ARRAY[]::TEXT[], notable_titles = ARRAY['Ahavamalla','Trilokamalla']::TEXT[],
  active_start_year = 1042, active_end_year = 1068, century = '11th century CE', timeline_order = 20,
  father = 'Jayasimha II', mother = NULL, spouse = NULL,
  children = ARRAY['Somesvara II','Vikramaditya VI']::TEXT[],
  teacher = NULL, students = NULL,
  predecessor = 'Jayasimha II', successor = 'Somesvara II',
  contemporaries = ARRAY['Rajadhiraja I','Rajendra II']::TEXT[],
  related_people = ARRAY['Jayasimha II','Somesvara II','Vikramaditya VI','Rajadhiraja I','Rajendra II']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Western Chalukya','Chola']::TEXT[],
  related_kingdoms = ARRAY['Deccan']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Someshvara_I',
  keywords = ARRAY['Somesvara I','Western Chalukya','Ahavamalla','Kalyani','Chola wars','Koppam','Battle of Koppam']::TEXT[],
  search_aliases = ARRAY['Someshvara I','Ahavamalla']::TEXT[],
  meta_description = 'Somesvara I (1042-1068 CE) shifted the Western Chalukya capital to Kalyani and defeated Chola king Rajadhiraja I at Koppam.',
  verified = TRUE, featured = FALSE, updated_at = NOW()
WHERE id = 'p40';

-- p41: Vikramaditya VI Chalukya
UPDATE personalities SET
  slug = 'vikramaditya-vi-chalukya', title = 'Emperor', gender = 'Male',
  birth_year = NULL, death_year = 1126, birth_text = NULL, death_text = '1126 CE',
  categories = ARRAY['Ruler','Patron of Arts','Patron of Literature']::TEXT[],
  civilization = 'Western Chalukya Dynasty', historical_period = 'Medieval India',
  dynasty = 'Western Chalukya', kingdom = 'Deccan', religion = 'Hinduism',
  occupation = ARRAY['Emperor']::TEXT[],
  birthplace = NULL, death_place = 'Kalyani',
  region = 'Deccan', present_state = 'Karnataka', present_country = 'India',
  short_description = 'Vikramaditya VI (r. 1076-1126 CE) was the greatest of the Western Chalukya kings, ruling for 50 years. He inaugurated the Chalukya Vikrama era in 1076 and was a renowned patron of scholars including Bilhana and Vijnaneshvara.',
  famous_for = 'Instituting the Chalukya Vikrama era (1076 CE) and patronizing some of the greatest scholars of medieval India. His 50-year reign marked the cultural zenith of the Western Chalukyas.',
  achievements = ARRAY['Instituted the Chalukya Vikrama era in 1076 CE','Ruled for 50 years, the longest Western Chalukya reign','Patronized poet Bilhana (Vikramankadevacharita)','Patronized jurist Vijnaneshvara (Mitakshara commentary)','Patronized Kannada grammarian Nagavarma II','Maintained peace and prosperity across the Deccan']::TEXT[],
  notable_works = ARRAY[]::TEXT[], notable_titles = ARRAY['Tribhuvanamalla','Permadideva']::TEXT[],
  active_start_year = 1076, active_end_year = 1126, century = '11th century CE', timeline_order = 21,
  father = 'Somesvara I', mother = NULL, spouse = NULL,
  children = ARRAY['Somesvara III']::TEXT[],
  teacher = NULL, students = NULL,
  predecessor = 'Somesvara II', successor = 'Somesvara III',
  contemporaries = ARRAY['Bilhana','Vijnaneshvara','Nagavarma II','Kulothunga I']::TEXT[],
  related_people = ARRAY['Somesvara I','Somesvara II','Somesvara III','Bilhana','Vijnaneshvara']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Western Chalukya','Chola','Hoysala','Kakatiya']::TEXT[],
  related_kingdoms = ARRAY['Deccan']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Vikramaditya_VI',
  keywords = ARRAY['Vikramaditya VI','Western Chalukya','Chalukya Vikrama era','Bilhana','Vijnaneshvara','Mitakshara','Kalyani']::TEXT[],
  search_aliases = ARRAY['Tribhuvanamalla','Permadideva']::TEXT[],
  meta_description = 'Vikramaditya VI (1076-1126 CE) was the greatest Western Chalukya king, patronizing Bilhana and Vijnaneshvara over a 50-year reign.',
  verified = TRUE, featured = TRUE, updated_at = NOW()
WHERE id = 'p41';

-- p42: Kakatiya Prataparudra
UPDATE personalities SET
  slug = 'kakatiya-prataparudra', title = 'King', gender = 'Male',
  birth_year = NULL, death_year = 1323, birth_text = NULL, death_text = '1323 CE',
  categories = ARRAY['Ruler','Military']::TEXT[],
  civilization = 'Kakatiya Dynasty', historical_period = 'Medieval India',
  dynasty = 'Kakatiya', kingdom = 'Andhra', religion = 'Hinduism',
  occupation = ARRAY['King']::TEXT[],
  birthplace = NULL, death_place = 'Warangal',
  region = 'Andhra', present_state = 'Telangana', present_country = 'India',
  short_description = 'Prataparudra II (r. 1289-1323 CE) was the last ruler of the Kakatiya dynasty who valiantly resisted multiple invasions from the Delhi Sultanate before being captured in 1323, marking the end of Kakatiya rule.',
  famous_for = 'Being the last Kakatiya king who fought against repeated Delhi Sultanate invasions. He was ultimately captured by the Tughluq forces in 1323, ending the Kakatiya dynasty.',
  achievements = ARRAY['Resisted multiple invasions from the Delhi Sultanate','Repelled Alauddin Khalji''s initial expeditions','Expanded the kingdom''s western frontier to Raichur','Built and fortified the Warangal Fort with its iconic gateways','Patronized Telugu literature and Palkuriki Somanatha']::TEXT[],
  notable_works = ARRAY[]::TEXT[], notable_titles = ARRAY['Rudradeva','Maharaja']::TEXT[],
  active_start_year = 1289, active_end_year = 1323, century = '13th century CE', timeline_order = 25,
  father = NULL, mother = 'Mummadamba', spouse = NULL, children = NULL,
  teacher = NULL, students = NULL,
  predecessor = 'Rudrama Devi', successor = NULL,
  contemporaries = ARRAY['Alauddin Khalji','Ghiyath al-Din Tughluq','Ulugh Khan']::TEXT[],
  related_people = ARRAY['Rudrama Devi','Ganapatideva','Alauddin Khalji','Ulugh Khan']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Kakatiya','Khalji dynasty','Tughluq dynasty']::TEXT[],
  related_kingdoms = ARRAY['Andhra']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Prataparudra_II',
  keywords = ARRAY['Prataparudra','Kakatiya','Warangal','Orugallu','Delhi Sultanate','Khalji','Tughluq','last Kakatiya king']::TEXT[],
  search_aliases = ARRAY['Prataparudra II','Rudradeva II']::TEXT[],
  meta_description = 'Prataparudra II (1289-1323 CE), last Kakatiya king, resisted Delhi Sultanate invasions before his capture ended the dynasty in 1323.',
  verified = TRUE, featured = FALSE, updated_at = NOW()
WHERE id = 'p42';

-- p43: Rudrama Devi
UPDATE personalities SET
  slug = 'rudrama-devi', title = 'Queen', gender = 'Female',
  birth_year = NULL, death_year = 1289, birth_text = NULL, death_text = 'c. 1289 CE',
  categories = ARRAY['Ruler','Military']::TEXT[],
  civilization = 'Kakatiya Dynasty', historical_period = 'Medieval India',
  dynasty = 'Kakatiya', kingdom = 'Andhra', religion = 'Hinduism',
  occupation = ARRAY['Queen']::TEXT[],
  birthplace = 'Warangal', death_place = 'Warangal',
  region = 'Andhra', present_state = 'Telangana', present_country = 'India',
  short_description = 'Rudrama Devi (r. c. 1262-1289 CE) was a warrior queen of the Kakatiya dynasty who ruled from Warangal. She was one of the few women to rule a South Indian kingdom as a queen regnant, adopting the male title Rudradeva.',
  famous_for = 'Being one of the few women sovereigns in Indian history who ruled as a queen regnant. She successfully defended her kingdom against the Seuna Yadavas and completed the Warangal Fort fortifications.',
  achievements = ARRAY['Ruled as queen regnant of the Kakatiya dynasty','Adopted male title Rudradeva to legitimize her rule','Successfully defended against the Seuna Yadava invasions','Completed the Warangal Fort fortifications including the iconic stone gateways','Mentored her grandson Prataparudra II as successor']::TEXT[],
  notable_works = ARRAY[]::TEXT[], notable_titles = ARRAY['Rudradeva','Maharaja']::TEXT[],
  active_start_year = 1262, active_end_year = 1289, century = '13th century CE', timeline_order = 24,
  father = 'Ganapatideva', mother = NULL,
  spouse = ARRAY['Virabhadra']::TEXT[],
  children = ARRAY[]::TEXT[],
  teacher = NULL, students = NULL,
  predecessor = 'Ganapatideva', successor = 'Prataparudra II',
  contemporaries = ARRAY['Mahadeva']::TEXT[],
  related_people = ARRAY['Ganapatideva','Prataparudra II','Virabhadra']::TEXT[],
  related_events = ARRAY[]::TEXT[], related_dynasties = ARRAY['Kakatiya','Seuna Yadava']::TEXT[],
  related_kingdoms = ARRAY['Andhra']::TEXT[],
  wikipedia_url = 'https://en.wikipedia.org/wiki/Rudrama_Devi',
  keywords = ARRAY['Rudrama Devi','Kakatiya','warrior queen','Warangal','queen regnant','Rudradeva','Ganapatideva','Telangana']::TEXT[],
  search_aliases = ARRAY['Rudramadevi','Rani Rudrama Devi']::TEXT[],
  meta_description = 'Rudrama Devi (1262-1289 CE) was a warrior queen regnant of the Kakatiya dynasty who ruled from Warangal as Rudradeva.',
  verified = TRUE, featured = TRUE, updated_at = NOW()
WHERE id = 'p43';
